


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."approve_quote"("p_quote_id" bigint) RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
declare
  q record; it record; ex record;
  cust_id bigint; reserved int := 0; conflicts text[] := '{}'; m_id bigint; job_title text;
begin
  select * into q from quotes where id = p_quote_id;
  if not found then return jsonb_build_object('done', false); end if;

  -- Müşteri bul/oluştur
  if coalesce(q.eposta,'') <> '' then
    select id into cust_id from customers where eposta = q.eposta limit 1;
  end if;
  if cust_id is null and coalesce(q.firma,'') <> '' then
    select id into cust_id from customers where firma = q.firma limit 1;
  end if;
  if cust_id is null then
    insert into customers (firma, ilgili_kisi, telefon, eposta)
    values (coalesce(nullif(q.firma,''), nullif(q.customer_name,''), 'Müşteri'), q.customer_name, q.telefon, q.eposta)
    returning id into cust_id;
  end if;

  -- Ayları rezerve et, çakışmaları topla
  for it in select * from quote_items
            where quote_id = p_quote_id and unit_id is not null and ym is not null loop
    select status, customer_id into ex from bookings where unit_id = it.unit_id and ym = it.ym;
    if found and ex.status = 'dolu' and coalesce(ex.customer_id, -1) <> cust_id then
      conflicts := array_append(conflicts, coalesce(it.unit_name,'?') || ' · ' || it.ym);
      continue;
    end if;
    insert into bookings (unit_id, ym, status, customer_id)
    values (it.unit_id, it.ym, 'dolu', cust_id)
    on conflict (unit_id, ym) do update set status='dolu', customer_id=excluded.customer_id;
    reserved := reserved + 1;
    if m_id is null then select mecra_id into m_id from units where id = it.unit_id; end if;
  end loop;

  -- İş kartı (aynı teklif için tekrar açma)
  job_title := coalesce(nullif(q.firma,''), nullif(q.customer_name,''), 'Müşteri') || ' — Teklif #' || p_quote_id;
  if not exists (select 1 from jobs where title = job_title) then
    insert into jobs (title, customer_id, mecra_id, status, note)
    values (job_title, cust_id, m_id, 'tasarim', 'Onaylanan tekliften otomatik oluşturuldu.');
  end if;

  update quotes set status = 'onaylandi' where id = p_quote_id;
  return jsonb_build_object('reserved', reserved, 'conflicts', to_jsonb(conflicts), 'customer_id', cust_id);
end $$;


ALTER FUNCTION "public"."approve_quote"("p_quote_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."suppliers_sync_legacy"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.firma := coalesce(new.firma, new.name);
  new.name  := coalesce(new.name,  new.firma);
  new.kategori := coalesce(new.kategori, new.type);
  new.type     := coalesce(new.type,     new.kategori);
  return new;
end $$;


ALTER FUNCTION "public"."suppliers_sync_legacy"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activity_log" (
    "id" bigint NOT NULL,
    "kullanici" "text",
    "islem" "text" NOT NULL,
    "bolum" "text",
    "kayit_id" "text",
    "detay" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."activity_log" OWNER TO "postgres";


ALTER TABLE "public"."activity_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."alt_mecralar" (
    "id" bigint NOT NULL,
    "mecra_id" bigint NOT NULL,
    "product_id" bigint,
    "name" "text" NOT NULL,
    "baslik" "text",
    "aciklama" "text",
    "image" "text",
    "galeri" "jsonb" DEFAULT '[]'::"jsonb",
    "yerlesim_plani" "text",
    "maps" "text",
    "avantajlar" "jsonb" DEFAULT '[]'::"jsonb",
    "gunluk_gosterim" "text",
    "toplam_alan" "text",
    "visible" "jsonb" DEFAULT '{}'::"jsonb",
    "sort" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "kapak" "text",
    "marquee" "text",
    "kapak_color" "text" DEFAULT '#101014'::"text",
    "kapak_opacity" numeric DEFAULT 0.4,
    "fiyat" "jsonb",
    "kapak_height" integer DEFAULT 600,
    "intro_baslik" "text",
    "kapak_mobil" "text",
    "image_mobil" "text",
    "slug" "text",
    "hidden" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."alt_mecralar" OWNER TO "postgres";


ALTER TABLE "public"."alt_mecralar" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."alt_mecralar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "id" bigint NOT NULL,
    "unit_id" bigint NOT NULL,
    "ym" character(7) NOT NULL,
    "status" "text" DEFAULT 'dolu'::"text" NOT NULL,
    "customer_id" bigint,
    "note" "text",
    CONSTRAINT "bookings_status_check" CHECK (("status" = ANY (ARRAY['dolu'::"text", 'rezerve'::"text"])))
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


ALTER TABLE "public"."bookings" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."bookings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" bigint NOT NULL,
    "firma" "text",
    "ilgili_kisi" "text",
    "birim" "text",
    "telefon" "text",
    "eposta" "text",
    "adres" "text",
    "vergi_no" "text",
    "vergi_dairesi" "text",
    "mersis" "text",
    "fatura_basligi" "text",
    "puan" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


ALTER TABLE "public"."customers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "customer_id" bigint,
    "mecra_id" bigint,
    "status" "text" DEFAULT 'tasarim'::"text" NOT NULL,
    "start_day" "date",
    "end_day" "date",
    "note" "text",
    "sort" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "supplier_id" bigint,
    CONSTRAINT "jobs_status_check" CHECK (("status" = ANY (ARRAY['tasarim'::"text", 'baski'::"text", 'montaj'::"text", 'yayin'::"text", 'arsiv'::"text"])))
);


ALTER TABLE "public"."jobs" OWNER TO "postgres";


ALTER TABLE "public"."jobs" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."jobs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" bigint NOT NULL,
    "ad" "text",
    "telefon" "text",
    "eposta" "text",
    "firma" "text",
    "hedef_kitle" "text",
    "mecralar" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "butce" "text",
    "okundu" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


ALTER TABLE "public"."leads" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."mecralar" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "badge" "text",
    "stats" "text",
    "theme_color" "text" DEFAULT '#3f6f63'::"text",
    "image" "text",
    "maps" "text",
    "aciklama" "text",
    "sort" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "baslik" "text",
    "gunluk_gosterim" "text",
    "toplam_alan" "text",
    "logo" "text",
    "avantajlar" "jsonb" DEFAULT '[]'::"jsonb",
    "galeri" "jsonb" DEFAULT '[]'::"jsonb",
    "yerlesim_plani" "text",
    "visible" "jsonb" DEFAULT '{}'::"jsonb",
    "kapak" "text",
    "kapak_color" "text" DEFAULT '#101014'::"text",
    "kapak_opacity" numeric DEFAULT 0.4,
    "kapak_height" integer DEFAULT 600,
    "intro_baslik" "text",
    "kroki_mobil" "text",
    "kapak_mobil" "text",
    "image_mobil" "text",
    "hub" boolean,
    "slug" "text",
    "hidden" boolean DEFAULT false NOT NULL,
    "katalog" "text",
    "intro_image" "text"
);


ALTER TABLE "public"."mecralar" OWNER TO "postgres";


ALTER TABLE "public"."mecralar" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."mecralar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notes" (
    "id" bigint NOT NULL,
    "konu" "text",
    "body" "text",
    "ilgili_kisi" "text",
    "tarih" "date",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notes" OWNER TO "postgres";


ALTER TABLE "public"."notes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."notes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pages" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text",
    "body" "text",
    "sort" integer DEFAULT 0,
    "blocks" "jsonb" DEFAULT '[]'::"jsonb",
    "in_menu" boolean DEFAULT true
);


ALTER TABLE "public"."pages" OWNER TO "postgres";


ALTER TABLE "public"."pages" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."pages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "olcu" "text",
    "yuzey" "text",
    "isikli" "text",
    "baski_malzemesi" "text",
    "baski_format" "text",
    "yayin_format" "text",
    "baski_ucreti" "text",
    "montaj_ucreti" "text",
    "extra_ucret" "text",
    "prices" "jsonb" DEFAULT '{}'::"jsonb",
    "sort" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "etiketler" "text",
    "ikon" "text"
);


ALTER TABLE "public"."products" OWNER TO "postgres";


ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."quote_items" (
    "id" bigint NOT NULL,
    "quote_id" bigint NOT NULL,
    "unit_id" bigint,
    "ym" character(7),
    "mecra_name" "text",
    "unit_name" "text",
    "product_name" "text",
    "olcu" "text",
    "start_day" "date",
    "period" "text",
    "price" numeric(12,2) DEFAULT 0,
    "adet" integer DEFAULT 1 NOT NULL,
    "aciklama" "text"
);


ALTER TABLE "public"."quote_items" OWNER TO "postgres";


ALTER TABLE "public"."quote_items" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."quote_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."quotes" (
    "id" bigint NOT NULL,
    "customer_name" "text",
    "firma" "text",
    "telefon" "text",
    "eposta" "text",
    "note" "text",
    "total" numeric(12,2) DEFAULT 0,
    "status" "text" DEFAULT 'yeni'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "okundu" boolean DEFAULT false,
    "customer_id" bigint,
    "kaynak" "text" DEFAULT 'site'::"text" NOT NULL,
    "gecerlilik" "date",
    "indirim" numeric DEFAULT 0 NOT NULL,
    "kdv" numeric DEFAULT 20 NOT NULL,
    CONSTRAINT "quotes_status_check" CHECK (("status" = ANY (ARRAY['yeni'::"text", 'gorusuldu'::"text", 'onaylandi'::"text", 'iptal'::"text"])))
);


ALTER TABLE "public"."quotes" OWNER TO "postgres";


ALTER TABLE "public"."quotes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."quotes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."settings" (
    "k" "text" NOT NULL,
    "v" "jsonb"
);


ALTER TABLE "public"."settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."suppliers" (
    "id" bigint NOT NULL,
    "name" "text",
    "type" "text",
    "telefon" "text",
    "eposta" "text",
    "note" "text",
    "firma" "text",
    "kategori" "text",
    "ilgili_kisi" "text",
    "iban" "text",
    "adres" "text",
    "vergi_no" "text",
    "vergi_dairesi" "text",
    "notlar" "text",
    "aktif" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."suppliers" OWNER TO "postgres";


ALTER TABLE "public"."suppliers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."suppliers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "role" "text",
    "yetki" "text",
    "telefon" "text",
    "eposta" "text",
    "photo" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."team" OWNER TO "postgres";


ALTER TABLE "public"."team" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."team_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tuyap_ayarlar" (
    "key" "text" NOT NULL,
    "value" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."tuyap_ayarlar" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tuyap_gruplar" (
    "id" "text" NOT NULL,
    "sira" integer DEFAULT 0 NOT NULL,
    "name" "text" NOT NULL,
    "cat" "text" DEFAULT ''::"text",
    "count_text" "text" DEFAULT ''::"text",
    "descr" "text" DEFAULT ''::"text",
    "why" "text" DEFAULT ''::"text",
    "specs" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "images" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "budget" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "visible" boolean DEFAULT true NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pdf_url" "text" DEFAULT ''::"text" NOT NULL,
    "pdf_name" "text" DEFAULT ''::"text" NOT NULL,
    "types" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "logo_url" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."tuyap_gruplar" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tuyap_noktalar" (
    "id" "text" NOT NULL,
    "grp" "text",
    "t" "text" DEFAULT 'led'::"text" NOT NULL,
    "lat" double precision NOT NULL,
    "lng" double precision NOT NULL,
    "name" "text" NOT NULL,
    "meta" "text" DEFAULT ''::"text",
    "why" "text" DEFAULT ''::"text",
    "hl" boolean DEFAULT false NOT NULL,
    "sira" integer DEFAULT 0 NOT NULL,
    "img" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."tuyap_noktalar" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."units" (
    "id" bigint NOT NULL,
    "mecra_id" bigint NOT NULL,
    "product_id" bigint,
    "name" "text" NOT NULL,
    "olcu" "text",
    "konum" "text",
    "image" "text",
    "sort" integer DEFAULT 0,
    "alt_mecra_id" bigint,
    "lat" double precision,
    "lng" double precision
);


ALTER TABLE "public"."units" OWNER TO "postgres";


ALTER TABLE "public"."units" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."units_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."activity_log"
    ADD CONSTRAINT "activity_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."alt_mecralar"
    ADD CONSTRAINT "alt_mecralar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_unit_id_ym_key" UNIQUE ("unit_id", "ym");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."mecralar"
    ADD CONSTRAINT "mecralar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pages"
    ADD CONSTRAINT "pages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pages"
    ADD CONSTRAINT "pages_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quote_items"
    ADD CONSTRAINT "quote_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quotes"
    ADD CONSTRAINT "quotes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("k");



ALTER TABLE ONLY "public"."suppliers"
    ADD CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team"
    ADD CONSTRAINT "team_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tuyap_ayarlar"
    ADD CONSTRAINT "tuyap_ayarlar_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."tuyap_gruplar"
    ADD CONSTRAINT "tuyap_gruplar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tuyap_noktalar"
    ADD CONSTRAINT "tuyap_noktalar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."units"
    ADD CONSTRAINT "units_pkey" PRIMARY KEY ("id");



CREATE INDEX "activity_log_time_idx" ON "public"."activity_log" USING "btree" ("created_at" DESC);



CREATE INDEX "alt_slug_idx" ON "public"."alt_mecralar" USING "btree" ("mecra_id", "slug");



CREATE INDEX "idx_alt_mecra" ON "public"."alt_mecralar" USING "btree" ("mecra_id");



CREATE INDEX "idx_bookings_unit" ON "public"."bookings" USING "btree" ("unit_id");



CREATE INDEX "idx_bookings_ym" ON "public"."bookings" USING "btree" ("ym");



CREATE INDEX "idx_quote_items_quote" ON "public"."quote_items" USING "btree" ("quote_id");



CREATE INDEX "idx_units_alt" ON "public"."units" USING "btree" ("alt_mecra_id");



CREATE INDEX "idx_units_mecra" ON "public"."units" USING "btree" ("mecra_id");



CREATE INDEX "jobs_supplier_idx" ON "public"."jobs" USING "btree" ("supplier_id");



CREATE UNIQUE INDEX "mecralar_slug_uq" ON "public"."mecralar" USING "btree" ("slug") WHERE ("slug" IS NOT NULL);



CREATE INDEX "quotes_okundu_idx" ON "public"."quotes" USING "btree" ("okundu") WHERE ("okundu" = false);



CREATE INDEX "units_latlng_idx" ON "public"."units" USING "btree" ("lat", "lng") WHERE (("lat" IS NOT NULL) AND ("lng" IS NOT NULL));



CREATE OR REPLACE TRIGGER "trg_suppliers_sync" BEFORE INSERT OR UPDATE ON "public"."suppliers" FOR EACH ROW EXECUTE FUNCTION "public"."suppliers_sync_legacy"();



ALTER TABLE ONLY "public"."alt_mecralar"
    ADD CONSTRAINT "alt_mecralar_mecra_id_fkey" FOREIGN KEY ("mecra_id") REFERENCES "public"."mecralar"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."alt_mecralar"
    ADD CONSTRAINT "alt_mecralar_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_mecra_id_fkey" FOREIGN KEY ("mecra_id") REFERENCES "public"."mecralar"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."quote_items"
    ADD CONSTRAINT "quote_items_quote_id_fkey" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quote_items"
    ADD CONSTRAINT "quote_items_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."units"
    ADD CONSTRAINT "units_alt_mecra_id_fkey" FOREIGN KEY ("alt_mecra_id") REFERENCES "public"."alt_mecralar"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."units"
    ADD CONSTRAINT "units_mecra_id_fkey" FOREIGN KEY ("mecra_id") REFERENCES "public"."mecralar"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."units"
    ADD CONSTRAINT "units_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE SET NULL;



ALTER TABLE "public"."activity_log" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "activity_log_auth" ON "public"."activity_log" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "alt_admin" ON "public"."alt_mecralar" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."alt_mecralar" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "alt_read" ON "public"."alt_mecralar" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."bookings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "bookings_admin" ON "public"."bookings" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "bookings_read" ON "public"."bookings" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "customers_admin" ON "public"."customers" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "jobs_admin" ON "public"."jobs" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."leads" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "leads_admin" ON "public"."leads" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "leads_insert" ON "public"."leads" FOR INSERT TO "anon" WITH CHECK (true);



ALTER TABLE "public"."mecralar" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "mecralar_admin" ON "public"."mecralar" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "mecralar_read" ON "public"."mecralar" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."notes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "notes_admin" ON "public"."notes" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."pages" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "pages_admin" ON "public"."pages" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "pages_read" ON "public"."pages" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "products_admin" ON "public"."products" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "products_read" ON "public"."products" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."quote_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "quote_items_admin" ON "public"."quote_items" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "quote_items_insert" ON "public"."quote_items" FOR INSERT TO "anon" WITH CHECK (true);



ALTER TABLE "public"."quotes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "quotes_admin" ON "public"."quotes" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "quotes_insert" ON "public"."quotes" FOR INSERT TO "anon" WITH CHECK (true);



ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "settings_admin" ON "public"."settings" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "settings_read" ON "public"."settings" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."suppliers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "suppliers_admin" ON "public"."suppliers" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "suppliers_auth_all" ON "public"."suppliers" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."team" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "team_admin" ON "public"."team" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."tuyap_ayarlar" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "tuyap_ayarlar read" ON "public"."tuyap_ayarlar" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "tuyap_ayarlar write" ON "public"."tuyap_ayarlar" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."tuyap_gruplar" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "tuyap_gruplar read" ON "public"."tuyap_gruplar" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "tuyap_gruplar write" ON "public"."tuyap_gruplar" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."tuyap_noktalar" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "tuyap_noktalar read" ON "public"."tuyap_noktalar" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "tuyap_noktalar write" ON "public"."tuyap_noktalar" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."units" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "units_admin" ON "public"."units" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "units_read" ON "public"."units" FOR SELECT TO "authenticated", "anon" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































REVOKE ALL ON FUNCTION "public"."approve_quote"("p_quote_id" bigint) FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."approve_quote"("p_quote_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."approve_quote"("p_quote_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."suppliers_sync_legacy"() TO "anon";
GRANT ALL ON FUNCTION "public"."suppliers_sync_legacy"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."suppliers_sync_legacy"() TO "service_role";


















GRANT ALL ON TABLE "public"."activity_log" TO "anon";
GRANT ALL ON TABLE "public"."activity_log" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activity_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activity_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activity_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."alt_mecralar" TO "anon";
GRANT ALL ON TABLE "public"."alt_mecralar" TO "authenticated";
GRANT ALL ON TABLE "public"."alt_mecralar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."alt_mecralar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."alt_mecralar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."alt_mecralar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."jobs" TO "anon";
GRANT ALL ON TABLE "public"."jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."leads" TO "anon";
GRANT ALL ON TABLE "public"."leads" TO "authenticated";
GRANT ALL ON TABLE "public"."leads" TO "service_role";



GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."mecralar" TO "anon";
GRANT ALL ON TABLE "public"."mecralar" TO "authenticated";
GRANT ALL ON TABLE "public"."mecralar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."mecralar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."mecralar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."mecralar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notes" TO "anon";
GRANT ALL ON TABLE "public"."notes" TO "authenticated";
GRANT ALL ON TABLE "public"."notes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pages" TO "anon";
GRANT ALL ON TABLE "public"."pages" TO "authenticated";
GRANT ALL ON TABLE "public"."pages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quote_items" TO "anon";
GRANT ALL ON TABLE "public"."quote_items" TO "authenticated";
GRANT ALL ON TABLE "public"."quote_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quote_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quote_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quote_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quotes" TO "anon";
GRANT ALL ON TABLE "public"."quotes" TO "authenticated";
GRANT ALL ON TABLE "public"."quotes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quotes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quotes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quotes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."settings" TO "anon";
GRANT ALL ON TABLE "public"."settings" TO "authenticated";
GRANT ALL ON TABLE "public"."settings" TO "service_role";



GRANT ALL ON TABLE "public"."suppliers" TO "anon";
GRANT ALL ON TABLE "public"."suppliers" TO "authenticated";
GRANT ALL ON TABLE "public"."suppliers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."team" TO "anon";
GRANT ALL ON TABLE "public"."team" TO "authenticated";
GRANT ALL ON TABLE "public"."team" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tuyap_ayarlar" TO "anon";
GRANT ALL ON TABLE "public"."tuyap_ayarlar" TO "authenticated";
GRANT ALL ON TABLE "public"."tuyap_ayarlar" TO "service_role";



GRANT ALL ON TABLE "public"."tuyap_gruplar" TO "anon";
GRANT ALL ON TABLE "public"."tuyap_gruplar" TO "authenticated";
GRANT ALL ON TABLE "public"."tuyap_gruplar" TO "service_role";



GRANT ALL ON TABLE "public"."tuyap_noktalar" TO "anon";
GRANT ALL ON TABLE "public"."tuyap_noktalar" TO "authenticated";
GRANT ALL ON TABLE "public"."tuyap_noktalar" TO "service_role";



GRANT ALL ON TABLE "public"."units" TO "anon";
GRANT ALL ON TABLE "public"."units" TO "authenticated";
GRANT ALL ON TABLE "public"."units" TO "service_role";



GRANT ALL ON SEQUENCE "public"."units_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."units_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."units_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































