-- =====================================================================
-- PS12 — Raporlar için baskı/montaj operasyon alanları (EKLEMELİ)
--
-- Baskı/montaj dökümü raporu, referans çalışma tablolarının (BASKI MONTAJ
-- TAKİP TABLOSU, Gürgençler bütçe tablosu) ayırdığı bilgileri taşıyabilmeli.
-- Uygulamada karşılığı OLMAYAN alanlar rapor için uydurulmaz; mevcut
-- operasyon kayıt akışına (tek kayıt formu + çok satırlı form) küçük,
-- eklemeli alanlar olarak eklenir. Rapora özel ikinci veri giriş sistemi YOK.
--
--   material        Malzeme / cins          ("Önden ışıklı vinil")
--   grammage_gsm    Gramaj (gr/m²)          (440)
--   dimensions      (MEVCUT) Baskı ölçüsü   ("290 x 590 cm")
--   visible_size    Görünen alan            ("282 x 583 cm") — baskı ölçüsünden AYRI
--   surface_count   Yüzey sayısı            — baskı adedinden AYRI
--   quantity        (MEVCUT) Miktar
--   quantity_unit   Miktarın birimi         ('adet' | 'gun' …) — "4 gün vinç"
--                   dört baskı sayılmaz
--   reprint         Yeniden baskı mı        (ölçü revizesi / yer değişikliği)
--   unit_cost       Birim maliyet
--   cost            (MEVCUT) Maliyet (satır toplamı)
--   sale_amount     Satış bedeli (satır)
--   currency        Para birimi — farklı birimler asla tek tutarda toplanmaz
--   price_group_id  Paket bedeli bağlantısı
--
-- PAKET BEDELİ: referans tablolarda bazı bedeller tek satırın değil bir grup
-- işlemin toplamıdır (birleştirilmiş hücre: "106.170 TL" 20 satırı kapsar;
-- Gürgençler'de satırlar toplamı 62.700 iken anlaşılan paket 60.000).
-- Tutar BİR KEZ saklanmalı; her satıra yazmak toplamda çoğalmaya yol açar.
-- Bu gerçek bir 1:N kardinalite olduğu için (D-228 ölçütü) tek küçük tablo
-- açılır: `operation_price_groups`. Paket yalnız kendi işinin operasyonlarını
-- kapsayabilir (tetikleyiciyle zorlanır).
--
-- Mevcut satırlar: yeni kolonlar NULL/varsayılan; hiçbir veri değişmez.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Paket bedeli tablosu
-- ---------------------------------------------------------------------
create table if not exists public.operation_price_groups (
  id                 bigint generated by default as identity primary key,
  job_id             bigint not null references public.jobs(id) on delete cascade,
  label              text   not null,
  cost_amount        numeric(14,2),
  sale_amount        numeric(14,2),
  currency           text   not null default 'TRY',
  note               text,
  created_by_team_id bigint references public.team(id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz,
  constraint operation_price_groups_label_nonempty check (length(btrim(label)) > 0),
  constraint operation_price_groups_cost_nonneg   check (cost_amount is null or cost_amount >= 0),
  constraint operation_price_groups_sale_nonneg   check (sale_amount is null or sale_amount >= 0),
  constraint operation_price_groups_currency      check (currency in ('TRY','USD','EUR'))
);
create index if not exists operation_price_groups_job_idx on public.operation_price_groups(job_id);

comment on table public.operation_price_groups is
  'PS12: Birden çok baskı/montaj işlemini kapsayan TEK bedel (paket). Tutar bir kez saklanır; raporda satırlara dağıtılmaz.';

-- ---------------------------------------------------------------------
-- 2. work_operations — eklemeli alanlar
-- ---------------------------------------------------------------------
alter table public.work_operations
  add column if not exists material       text,
  add column if not exists grammage_gsm   integer,
  add column if not exists visible_size   text,
  add column if not exists surface_count  integer,
  add column if not exists quantity_unit  text    not null default 'adet',
  add column if not exists reprint        boolean not null default false,
  add column if not exists unit_cost      numeric(14,2),
  add column if not exists sale_amount    numeric(14,2),
  add column if not exists currency       text    not null default 'TRY',
  add column if not exists price_group_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'work_operations_grammage_pos') then
    alter table public.work_operations add constraint work_operations_grammage_pos
      check (grammage_gsm is null or grammage_gsm > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_surface_nonneg') then
    alter table public.work_operations add constraint work_operations_surface_nonneg
      check (surface_count is null or surface_count >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_quantity_unit') then
    alter table public.work_operations add constraint work_operations_quantity_unit
      check (quantity_unit in ('adet','m2','metre','gun','saat','takim','hizmet'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_unit_cost_nonneg') then
    alter table public.work_operations add constraint work_operations_unit_cost_nonneg
      check (unit_cost is null or unit_cost >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_sale_nonneg') then
    alter table public.work_operations add constraint work_operations_sale_nonneg
      check (sale_amount is null or sale_amount >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_currency') then
    alter table public.work_operations add constraint work_operations_currency
      check (currency in ('TRY','USD','EUR'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'work_operations_price_group_fkey') then
    alter table public.work_operations add constraint work_operations_price_group_fkey
      foreign key (price_group_id) references public.operation_price_groups(id) on delete set null;
  end if;
end $$;
create index if not exists work_operations_price_group_idx on public.work_operations(price_group_id);

comment on column public.work_operations.dimensions    is 'Baskı ölçüsü (PS12 ile etiketi netleşti; görünen alan visible_size).';
comment on column public.work_operations.quantity      is 'Miktar; birimi quantity_unit. Baskı satırında baskı adedi.';
comment on column public.work_operations.cost          is 'Maliyet (satır toplamı). Paket bedeli ayrıca operation_price_groups.';

-- Paket yalnız KENDİ işinin operasyonlarını kapsar.
create or replace function public._trg_ops_paket_ayni_is()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  if new.price_group_id is not null and not exists (
       select 1 from public.operation_price_groups g
        where g.id = new.price_group_id and g.job_id = new.job_id) then
    raise exception 'Paket bedeli yalnız aynı işin kayıtlarını kapsayabilir.' using errcode = '23514';
  end if;
  return new;
end $$;
revoke all on function public._trg_ops_paket_ayni_is() from public, anon, authenticated;
drop trigger if exists trg_ops_paket_ayni_is on public.work_operations;
create trigger trg_ops_paket_ayni_is
  before insert or update of price_group_id, job_id on public.work_operations
  for each row execute function public._trg_ops_paket_ayni_is();

-- ---------------------------------------------------------------------
-- 3. RLS — work_operations ile birebir aynı model
-- ---------------------------------------------------------------------
alter table public.operation_price_groups enable row level security;
drop policy if exists ps12_opg_read   on public.operation_price_groups;
drop policy if exists ps12_opg_write  on public.operation_price_groups;
drop policy if exists ps12_opg_modify on public.operation_price_groups;
drop policy if exists ps12_opg_remove on public.operation_price_groups;
create policy ps12_opg_read   on public.operation_price_groups for select using (public.is_internal());
create policy ps12_opg_write  on public.operation_price_groups for insert with check (public.is_internal());
create policy ps12_opg_modify on public.operation_price_groups for update using (public.is_internal()) with check (public.is_internal());
create policy ps12_opg_remove on public.operation_price_groups for delete using (public.is_admin());
revoke all on public.operation_price_groups from anon;
grant select, insert, update, delete on public.operation_price_groups to authenticated;

-- ---------------------------------------------------------------------
-- 4. operations_batch_create — yeni alanlar + isteğe bağlı paket bedeli
--    İmza değiştiği için eski sürüm kaldırılır (aynı işlemde yenisi gelir).
--    `p_package` verilirse paket ve TÜM satırların paket bağlantısı aynı
--    işlemde yazılır: ya hepsi ya hiçbiri.
-- ---------------------------------------------------------------------
drop function if exists public.operations_batch_create(bigint, jsonb, jsonb);
create or replace function public.operations_batch_create(p_job bigint, p_rows jsonb,
                                                         p_docs jsonb default '[]'::jsonb,
                                                         p_package jsonb default null)
returns jsonb language plpgsql security invoker
set search_path = public, pg_temp as $$
declare
  r jsonb; n int := 0; ids bigint[]; docs jsonb := '[]'::jsonb; d jsonb; links jsonb;
  doc_ids jsonb := '[]'::jsonb; grp bigint := null;
begin
  if p_job is null then
    raise exception 'İş seçimi zorunlu.' using errcode = '22023';
  end if;
  if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'Kaydedilecek satır yok.' using errcode = '22023';
  end if;
  if jsonb_array_length(p_rows) > 60 then
    raise exception 'Tek seferde en fazla 60 satır kaydedilebilir.' using errcode = '22023';
  end if;

  for r in select * from jsonb_array_elements(p_rows) loop
    n := n + 1;
    if coalesce(r->>'operation_type', '') not in ('baski','montaj','sokum','diger') then
      raise exception 'Satır %: tür seçilmeli.', n using errcode = '23514';
    end if;
    if coalesce(nullif(trim(r->>'description'), ''), nullif(trim(r->>'location_text'), ''),
                r->>'unit_id') is null then
      raise exception 'Satır %: pozisyon, yer ya da açıklama girilmeli.', n using errcode = '23514';
    end if;
    if (r->>'quantity') is not null and (r->>'quantity')::numeric <= 0 then
      raise exception 'Satır %: miktar sıfırdan büyük olmalı.', n using errcode = '23514';
    end if;
    if coalesce(nullif(r->>'quantity_unit', ''), 'adet') not in ('adet','m2','metre','gun','saat','takim','hizmet') then
      raise exception 'Satır %: miktar birimi geçersiz.', n using errcode = '23514';
    end if;
    if (r->>'cost') is not null and (r->>'cost')::numeric < 0 then
      raise exception 'Satır %: maliyet negatif olamaz.', n using errcode = '23514';
    end if;
    if (r->>'surface_count') is not null and (r->>'surface_count')::int < 0 then
      raise exception 'Satır %: yüzey sayısı negatif olamaz.', n using errcode = '23514';
    end if;
  end loop;

  if p_package is not null and jsonb_typeof(p_package) = 'object' then
    if coalesce(nullif(trim(p_package->>'label'), ''), '') = '' then
      raise exception 'Paket bedeli için kısa bir ad girilmeli.' using errcode = '23514';
    end if;
    if (p_package->>'cost_amount') is null and (p_package->>'sale_amount') is null then
      raise exception 'Paket bedeli için maliyet ya da satış tutarı girilmeli.' using errcode = '23514';
    end if;
    insert into public.operation_price_groups (job_id, label, cost_amount, sale_amount, currency, note, created_by_team_id)
    values (p_job, trim(p_package->>'label'), (p_package->>'cost_amount')::numeric,
            (p_package->>'sale_amount')::numeric, coalesce(nullif(p_package->>'currency', ''), 'TRY'),
            nullif(trim(p_package->>'note'), ''), public.current_team_id())
    returning id into grp;
  end if;

  with ins as (
    insert into public.work_operations (job_id, operation_type, status, description, quantity,
                                        dimensions, supplier_org_id, unit_id, location_text,
                                        planned_date, cost, note, completed_at, created_by_team_id,
                                        material, grammage_gsm, visible_size, surface_count,
                                        quantity_unit, reprint, unit_cost, sale_amount, currency,
                                        price_group_id)
    select p_job, x->>'operation_type', coalesce(nullif(x->>'status', ''), 'planned'),
           nullif(trim(x->>'description'), ''), (x->>'quantity')::numeric,
           nullif(trim(x->>'dimensions'), ''), (x->>'supplier_org_id')::bigint,
           (x->>'unit_id')::bigint, nullif(trim(x->>'location_text'), ''),
           (x->>'planned_date')::date, (x->>'cost')::numeric, nullif(trim(x->>'note'), ''),
           case when x->>'status' = 'done' then now() end,
           public.current_team_id(),
           nullif(trim(x->>'material'), ''), (x->>'grammage_gsm')::int,
           nullif(trim(x->>'visible_size'), ''), (x->>'surface_count')::int,
           coalesce(nullif(x->>'quantity_unit', ''), 'adet'), coalesce((x->>'reprint')::boolean, false),
           (x->>'unit_cost')::numeric, (x->>'sale_amount')::numeric,
           coalesce(nullif(x->>'currency', ''), 'TRY'), grp
      from jsonb_array_elements(p_rows) with ordinality e(x, i)
     order by i
    returning id)
  select array_agg(id order by id) into ids from ins;

  if jsonb_typeof(p_docs) = 'array' and jsonb_array_length(p_docs) > 0 then
    select jsonb_agg(jsonb_build_object('operation_id', i)) into links from unnest(ids) as i;
    for d in select * from jsonb_array_elements(p_docs) loop
      docs := docs || jsonb_build_array(jsonb_set(d, '{links}', links));
    end loop;
    doc_ids := public.document_create(docs);
  end if;

  return jsonb_build_object('ids', to_jsonb(ids), 'documents', doc_ids, 'price_group_id', grp);
end;
$$;
revoke all on function public.operations_batch_create(bigint, jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.operations_batch_create(bigint, jsonb, jsonb, jsonb) to authenticated;
