-- Product Simplification Sprint 7 — Commercial Records foundation
--
-- CANONICAL NOTE: 06 §14 / D-229 embed a single primary Contract on `jobs`
-- (`contract_*`) and allow a separate `contracts` table "only when a real
-- multi-contract / amendment need exists". The reviewed Medyapark contracts
-- prove that need: one agreement carries several surfaces, media types,
-- periods and prices (MIÇI M1: two Megalight faces on one line; Onatça: two
-- wall locations with different prices; Eral: rent line + separate montaj
-- line), and company-level agreements exist outside a single Work. The
-- embedded fields cannot hold that without flattening. This migration opens
-- exactly the conditional table 06 §14 foresaw — nothing more.
--
-- MODEL
--   contracts        commercial agreement header (NOT the PDF binary)
--   contract_items   1..N commercial lines (surface/group, qty, period, amount)
--   document_links   gains `contract_id` (still exactly one target per row)
--
-- NOT HERE (explicit non-goals): no booking/occupancy/LED placement is created
-- from a contract item (Sprint 8); no invoice/payment engine; no quote
-- redesign — `quotes` stays the one structured Offer object.
--
-- `jobs.contract_*` becomes COMPATIBILITY-ONLY: `contract_status` is derived
-- from structured contracts by trigger whenever the Work has any; the UI no
-- longer edits these columns. Existing columns are not dropped.

-- =====================================================================
-- 1. contracts
-- =====================================================================
create table if not exists public.contracts (
  id                  bigint generated by default as identity primary key,
  customer_id         bigint not null references public.customers(id) on delete restrict,
  job_id              bigint null     references public.jobs(id)      on delete set null,
  quote_id            bigint null     references public.quotes(id)    on delete set null,
  title               text   not null,
  reference_no        text   null,
  status              text   not null default 'taslak',
  signed_at           date   null,
  currency            text   not null default 'TRY',
  vat_mode            text   not null default 'haric',
  vat_rate            numeric(5,2) null default 20,
  payment_terms       text   null,
  note                text   null,
  cancelled_at        timestamptz null,
  created_by_team_id  bigint null references public.team(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz null,
  constraint contracts_title_len    check (length(trim(title)) between 1 and 200),
  constraint contracts_status_check check (status in ('taslak','imzali','iptal')),
  constraint contracts_currency_chk check (currency ~ '^[A-Z]{3}$'),
  -- +KDV (haric) / KDV dahil (dahil) / not stated (belirtilmemis). No tax engine.
  constraint contracts_vat_mode_chk check (vat_mode in ('haric','dahil','belirtilmemis')),
  constraint contracts_vat_rate_chk check (vat_rate is null or (vat_rate >= 0 and vat_rate <= 100))
);

create index if not exists contracts_customer_idx on public.contracts (customer_id, created_at desc);
create index if not exists contracts_job_idx      on public.contracts (job_id) where job_id is not null;
create index if not exists contracts_quote_idx    on public.contracts (quote_id) where quote_id is not null;
create index if not exists contracts_status_idx   on public.contracts (status);

-- =====================================================================
-- 2. contract_items
-- =====================================================================
-- Line amount is the contractual truth. `unit_price` is optional: the real
-- contracts state a LINE total (e.g. 2 faces -> 110.000 TL). The UI may
-- default line_total = quantity x unit_price, but never overwrites an
-- explicitly entered line_total.
create table if not exists public.contract_items (
  id             bigint generated by default as identity primary key,
  contract_id    bigint not null references public.contracts(id) on delete cascade,
  item_type      text   not null default 'mecra',
  description    text   null,
  -- Optional, non-blocking media references. A reference never mutates
  -- Media and never creates a booking.
  mecra_id       bigint null references public.mecralar(id) on delete set null,
  unit_id        bigint null references public.units(id)    on delete set null,
  quantity       numeric(10,2) not null default 1,
  start_date     date null,
  end_date       date null,
  duration_note  text null,        -- "12 Ay", "3 ay", "15 sn"
  unit_price     numeric(14,2) null,
  line_total     numeric(14,2) null,
  note           text null,
  sort           integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz null,
  constraint contract_items_type_chk  check (item_type in ('mecra','baski','montaj','produksiyon','hizmet','diger')),
  constraint contract_items_qty_chk   check (quantity > 0),
  constraint contract_items_dates_chk check (end_date is null or start_date is null or end_date >= start_date),
  constraint contract_items_money_chk check ((unit_price is null or unit_price >= 0)
                                         and (line_total is null or line_total >= 0)),
  -- A line must say WHAT it is: a description or a media reference.
  constraint contract_items_meaning_chk check (
    nullif(trim(coalesce(description, '')), '') is not null or unit_id is not null or mecra_id is not null)
);

create index if not exists contract_items_contract_idx on public.contract_items (contract_id, sort, id);
create index if not exists contract_items_unit_idx     on public.contract_items (unit_id) where unit_id is not null;
create index if not exists contract_items_dates_idx    on public.contract_items (start_date, end_date);

-- =====================================================================
-- 3. document_links: Contract target
-- =====================================================================
alter table public.document_links
  add column if not exists contract_id bigint null references public.contracts(id) on delete cascade;

alter table public.document_links drop constraint if exists document_links_one_target;
alter table public.document_links add constraint document_links_one_target check (
  num_nonnulls(job_id, entry_id, operation_id, customer_id, contact_id, quote_id, contract_id) = 1);

create unique index if not exists document_links_contract_uq
  on public.document_links (document_id, contract_id) where contract_id is not null;
create index if not exists document_links_contract_idx
  on public.document_links (contract_id) where contract_id is not null;

-- S6 `document_create` wrote only the six original targets; a Contract link
-- would reach the CHECK with zero targets. Same function, one more target.
create or replace function public.document_create(p_docs jsonb)
returns jsonb language plpgsql security invoker
set search_path = public, pg_temp as $$
declare
  d jsonb; l jsonb; yeni bigint; ids bigint[] := '{}';
begin
  if jsonb_typeof(p_docs) <> 'array' or jsonb_array_length(p_docs) = 0 then
    raise exception 'Eklenecek belge yok.' using errcode = '22023';
  end if;
  if jsonb_array_length(p_docs) > 10 then
    raise exception 'Tek seferde en fazla 10 belge eklenebilir.' using errcode = '22023';
  end if;
  for d in select * from jsonb_array_elements(p_docs) loop
    insert into public.documents (original_name, title, doc_type, mime_type, size_bytes,
                                  provider, storage_bucket, storage_path, external_url, note)
    values (d->>'original_name', nullif(trim(d->>'title'), ''), coalesce(d->>'doc_type', 'diger'),
            d->>'mime_type', (d->>'size_bytes')::bigint,
            d->>'provider',
            case when d->>'provider' = 'supabase' then 'documents' end,
            case when d->>'provider' = 'supabase' then d->>'storage_path' end,
            case when d->>'provider' = 'external' then trim(d->>'external_url') end,
            nullif(trim(d->>'note'), ''))
    returning id into yeni;
    if jsonb_typeof(d->'links') <> 'array' or jsonb_array_length(d->'links') = 0 then
      raise exception 'Belge bir bağlama bağlanmalı.' using errcode = '23514';
    end if;
    for l in select * from jsonb_array_elements(d->'links') loop
      insert into public.document_links (document_id, job_id, entry_id, operation_id,
                                         customer_id, contact_id, quote_id, contract_id)
      values (yeni, (l->>'job_id')::bigint, (l->>'entry_id')::bigint, (l->>'operation_id')::bigint,
              (l->>'customer_id')::bigint, (l->>'contact_id')::bigint, (l->>'quote_id')::bigint,
              (l->>'contract_id')::bigint);
    end loop;
    ids := ids || yeni;
  end loop;
  return to_jsonb(ids);
end;
$$;
revoke all on function public.document_create(jsonb) from public, anon;
grant execute on function public.document_create(jsonb) to authenticated;

-- =====================================================================
-- 4. Trusted system activity kinds
-- =====================================================================
alter table public.entries drop constraint if exists entries_system_kind_check;
alter table public.entries add constraint entries_system_kind_check check (
  system_kind is null or system_kind in (
    'work_created','work_phase','work_lifecycle','work_contract','work_accounting',
    'operation_created','operation_status',
    'quote_revised','quote_approved',
    'document_added',
    'contract_created','contract_signed','contract_cancelled'));

-- =====================================================================
-- 5. contracts triggers
-- =====================================================================
-- Identity + lifecycle guard. A policy cannot compare OLD/NEW, so the rules
-- live here:
--   * creator comes from the JWT (admin may keep a supplied value: restore)
--   * created_by / created_at immutable
--   * cancelled is terminal for non-admins
--   * a signed contract cannot silently go back to draft (that would re-open
--     hard delete of commercial truth) except by an admin
--   * cancelled_at is system-stamped
create or replace function public._trg_contracts_kimlik() returns trigger
language plpgsql security definer
set search_path = public, auth, pg_temp as $$
begin
  if tg_op = 'INSERT' then
    if not public.is_admin() or new.created_by_team_id is null then
      new.created_by_team_id := public.current_team_id();
    end if;
    new.created_at := now();
    new.updated_at := null;
    new.cancelled_at := case when new.status = 'iptal' then now() end;
    return new;
  end if;

  if new.created_by_team_id is distinct from old.created_by_team_id
     or new.created_at is distinct from old.created_at then
    raise exception 'Sözleşmenin oluşturan bilgisi değiştirilemez.' using errcode = '42501';
  end if;
  if not public.is_admin() then
    if old.status = 'iptal' and new.status <> 'iptal' then
      raise exception 'İptal edilmiş sözleşme yeniden açılamaz.' using errcode = '42501';
    end if;
    if old.status = 'imzali' and new.status = 'taslak' then
      raise exception 'İmzalı sözleşme taslağa döndürülemez; gerekiyorsa iptal edin.' using errcode = '42501';
    end if;
  end if;
  if new.status = 'iptal' and old.status <> 'iptal' then new.cancelled_at := now();
  elsif new.status <> 'iptal' then new.cancelled_at := null;
  else new.cancelled_at := old.cancelled_at;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_contracts_kimlik on public.contracts;
create trigger trg_contracts_kimlik before insert or update on public.contracts
  for each row execute function public._trg_contracts_kimlik();

-- A SIGNED contract must carry at least one commercial line. Checked at
-- COMMIT so header + items are saved in one transaction (`contract_save`).
-- A draft may be empty while it is being prepared.
create or replace function public._sozlesme_kalem_kontrol(p_id bigint) returns void
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if exists (select 1 from public.contracts c where c.id = p_id and c.status = 'imzali')
     and not exists (select 1 from public.contract_items i where i.contract_id = p_id) then
    raise exception 'İmzalı bir sözleşmenin en az bir kalemi olmalı.' using errcode = '23514';
  end if;
end;
$$;
revoke all on function public._sozlesme_kalem_kontrol(bigint) from public, anon, authenticated;

create or replace function public._trg_contracts_kalem() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  perform public._sozlesme_kalem_kontrol(new.id);
  return null;
end;
$$;
drop trigger if exists trg_contracts_kalem on public.contracts;
create constraint trigger trg_contracts_kalem
  after insert or update of status on public.contracts
  deferrable initially deferred
  for each row execute function public._trg_contracts_kalem();

create or replace function public._trg_contract_items_kalem() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  perform public._sozlesme_kalem_kontrol(old.contract_id);
  return null;
end;
$$;
drop trigger if exists trg_contract_items_kalem on public.contract_items;
create constraint trigger trg_contract_items_kalem
  after delete on public.contract_items
  deferrable initially deferred
  for each row execute function public._trg_contract_items_kalem();

-- Lines of a cancelled contract are frozen for non-admins (history).
create or replace function public._trg_contract_items_koru() returns trigger
language plpgsql security definer
set search_path = public, auth, pg_temp as $$
declare st text; cid bigint;
begin
  cid := coalesce(new.contract_id, old.contract_id);
  select status into st from public.contracts where id = cid;
  if st = 'iptal' and not public.is_admin() then
    raise exception 'İptal edilmiş sözleşmenin kalemleri değiştirilemez.' using errcode = '42501';
  end if;
  if tg_op = 'UPDATE' then
    if new.contract_id is distinct from old.contract_id then
      raise exception 'Kalem başka sözleşmeye taşınamaz.' using errcode = '42501';
    end if;
    new.updated_at := now();
    new.created_at := old.created_at;
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
drop trigger if exists trg_contract_items_koru on public.contract_items;
create trigger trg_contract_items_koru before insert or update or delete on public.contract_items
  for each row execute function public._trg_contract_items_koru();

-- =====================================================================
-- 6. Compatibility: jobs.contract_status derived from structured contracts
-- =====================================================================
-- Deterministic rule for a Work that has ANY structured contract:
--   any signed -> 'signed', else any draft -> 'pending', else (all cancelled)
--   -> 'missing'. A Work whose last contract was deleted -> 'missing'.
-- A Work with no structured contracts at all keeps its legacy value.
-- The sync must not emit the S4.4 `work_contract` movement: the contract
-- trigger already emits the ONE meaningful business event.
create or replace function public._is_sozlesme_senk(p_job bigint) returns void
language plpgsql security definer
set search_path = public, pg_temp as $$
declare yeni text;
begin
  if p_job is null then return; end if;
  select case when bool_or(status = 'imzali') then 'signed'
              when bool_or(status = 'taslak') then 'pending'
              else 'missing' end
    into yeni from public.contracts where job_id = p_job;
  yeni := coalesce(yeni, 'missing');
  perform set_config('medyapark.sozlesme_senk', '1', true);
  update public.jobs set contract_status = yeni
   where id = p_job and contract_status is distinct from yeni;
  perform set_config('medyapark.sozlesme_senk', '', true);
end;
$$;
revoke all on function public._is_sozlesme_senk(bigint) from public, anon, authenticated;

-- Trusted movements for the three meaningful contract actions only.
-- Title/note/payment edits and line edits emit nothing (no noise).
-- Movements live on the Work timeline, so a Work-less (company-level)
-- contract produces none (entries history is Work-scoped, S4.4).
create or replace function public._trg_contracts_hareket() returns trigger
language plpgsql security definer
set search_path = public, auth, pg_temp as $$
begin
  if tg_op = 'INSERT' then
    perform public._sistem_hareketi(new.job_id, 'contract_created',
      'Sözleşme kaydı oluşturuldu: ' || new.title
      || case when new.status = 'imzali' then ' (imzalı)' else '' end);
    perform public._is_sozlesme_senk(new.job_id);
    return new;
  end if;
  if tg_op = 'DELETE' then
    perform public._is_sozlesme_senk(old.job_id);
    return old;
  end if;
  if new.status is distinct from old.status then
    if new.status = 'imzali' then
      perform public._sistem_hareketi(new.job_id, 'contract_signed',
        'Sözleşme imzalı olarak işaretlendi: ' || new.title);
    elsif new.status = 'iptal' then
      perform public._sistem_hareketi(new.job_id, 'contract_cancelled',
        'Sözleşme iptal edildi: ' || new.title);
    end if;
  end if;
  if new.job_id is distinct from old.job_id then
    perform public._is_sozlesme_senk(old.job_id);
  end if;
  if new.status is distinct from old.status or new.job_id is distinct from old.job_id then
    perform public._is_sozlesme_senk(new.job_id);
  end if;
  return new;
end;
$$;
drop trigger if exists trg_contracts_hareket on public.contracts;
create trigger trg_contracts_hareket after insert or update or delete on public.contracts
  for each row execute function public._trg_contracts_hareket();

-- S4.4 jobs trigger, unchanged except: a contract_status change caused by
-- the structured-contract sync emits no second movement.
create or replace function public._trg_jobs_hareket() returns trigger
language plpgsql security definer
set search_path = public, auth, pg_temp as $$
begin
  if tg_op = 'INSERT' then
    perform public._sistem_hareketi(new.id, 'work_created', 'İş oluşturuldu.');
    return new;
  end if;

  if new.status is distinct from old.status then
    perform public._sistem_hareketi(new.id, 'work_phase',
      'Aşama değişti: ' || public._lbl('faz', old.status) || ' → ' || public._lbl('faz', new.status));
  end if;

  if new.lifecycle_status is distinct from old.lifecycle_status then
    perform public._sistem_hareketi(new.id, 'work_lifecycle',
      'Durum değişti: ' || public._lbl('yasam', old.lifecycle_status) || ' → '
      || public._lbl('yasam', new.lifecycle_status)
      || case when new.lifecycle_status = 'kapandi' and new.closed_reason is not null
              then ' (' || public._lbl('kapanis', new.closed_reason) || ')' else '' end);
  end if;

  if new.contract_status is distinct from old.contract_status
     and coalesce(current_setting('medyapark.sozlesme_senk', true), '') <> '1' then
    perform public._sistem_hareketi(new.id, 'work_contract',
      'Sözleşme durumu: ' || public._lbl('sozlesme', old.contract_status) || ' → '
      || public._lbl('sozlesme', new.contract_status));
  end if;

  if new.accounting_status is distinct from old.accounting_status then
    perform public._sistem_hareketi(new.id, 'work_accounting',
      'Muhasebe durumu: ' || public._lbl('muhasebe', old.accounting_status) || ' → '
      || public._lbl('muhasebe', new.accounting_status));
  end if;

  return new;
end;
$$;

-- =====================================================================
-- 7. RLS
-- =====================================================================
alter table public.contracts      enable row level security;
alter table public.contract_items enable row level security;
revoke all on public.contracts      from anon;
revoke all on public.contract_items from anon;
grant select, insert, update, delete on public.contracts      to authenticated;
grant select, insert, update, delete on public.contract_items to authenticated;

drop policy if exists "s7_contracts_read"   on public.contracts;
drop policy if exists "s7_contracts_write"  on public.contracts;
drop policy if exists "s7_contracts_modify" on public.contracts;
drop policy if exists "s7_contracts_remove" on public.contracts;
create policy "s7_contracts_read"   on public.contracts for select to authenticated using (public.is_internal());
create policy "s7_contracts_write"  on public.contracts for insert to authenticated with check (public.is_internal());
create policy "s7_contracts_modify" on public.contracts for update to authenticated
  using (public.is_internal()) with check (public.is_internal());
-- Only a DRAFT may be deleted (its creator or an admin). Signed/cancelled
-- contracts are commercial history: cancel, do not delete.
create policy "s7_contracts_remove" on public.contracts for delete to authenticated
  using (status = 'taslak' and (public.is_admin() or created_by_team_id = public.current_team_id()));

drop policy if exists "s7_contract_items_read"   on public.contract_items;
drop policy if exists "s7_contract_items_write"  on public.contract_items;
drop policy if exists "s7_contract_items_modify" on public.contract_items;
drop policy if exists "s7_contract_items_remove" on public.contract_items;
create policy "s7_contract_items_read"   on public.contract_items for select to authenticated using (public.is_internal());
create policy "s7_contract_items_write"  on public.contract_items for insert to authenticated with check (public.is_internal());
create policy "s7_contract_items_modify" on public.contract_items for update to authenticated
  using (public.is_internal()) with check (public.is_internal());
create policy "s7_contract_items_remove" on public.contract_items for delete to authenticated
  using (public.is_internal());

-- =====================================================================
-- 8. Atomic save: header + lines (+ explicit document links) in ONE
--    transaction. SECURITY INVOKER: every RLS rule and trigger applies.
-- =====================================================================
-- p_contract: header fields (id for update). p_items: full line set; lines
-- with an id are updated, without id inserted, missing ids deleted.
-- p_doc_ids: existing documents to link to this contract (document-first
-- flow). No binary is copied; only a link row is added.
create or replace function public.contract_save(p_contract jsonb, p_items jsonb, p_doc_ids bigint[])
returns bigint language plpgsql security invoker
set search_path = public, pg_temp as $$
declare
  cid bigint := nullif(p_contract->>'id', '')::bigint;
  it jsonb; keep bigint[] := '{}'; iid bigint; n int := 0;
begin
  if cid is null then
    insert into public.contracts (customer_id, job_id, quote_id, title, reference_no, status,
      signed_at, currency, vat_mode, vat_rate, payment_terms, note)
    values ((p_contract->>'customer_id')::bigint, nullif(p_contract->>'job_id','')::bigint,
      nullif(p_contract->>'quote_id','')::bigint, p_contract->>'title',
      nullif(trim(p_contract->>'reference_no'),''), coalesce(p_contract->>'status','taslak'),
      nullif(p_contract->>'signed_at','')::date, coalesce(nullif(p_contract->>'currency',''),'TRY'),
      coalesce(nullif(p_contract->>'vat_mode',''),'haric'), nullif(p_contract->>'vat_rate','')::numeric,
      nullif(trim(p_contract->>'payment_terms'),''), nullif(trim(p_contract->>'note'),''))
    returning id into cid;
  else
    update public.contracts set
      customer_id   = (p_contract->>'customer_id')::bigint,
      job_id        = nullif(p_contract->>'job_id','')::bigint,
      quote_id      = nullif(p_contract->>'quote_id','')::bigint,
      title         = p_contract->>'title',
      reference_no  = nullif(trim(p_contract->>'reference_no'),''),
      status        = coalesce(p_contract->>'status','taslak'),
      signed_at     = nullif(p_contract->>'signed_at','')::date,
      currency      = coalesce(nullif(p_contract->>'currency',''),'TRY'),
      vat_mode      = coalesce(nullif(p_contract->>'vat_mode',''),'haric'),
      vat_rate      = nullif(p_contract->>'vat_rate','')::numeric,
      payment_terms = nullif(trim(p_contract->>'payment_terms'),''),
      note          = nullif(trim(p_contract->>'note'),'')
    where id = cid;
    get diagnostics n = row_count;
    if n = 0 then raise exception 'Bu sözleşmeyi değiştirme yetkiniz yok.' using errcode = '42501'; end if;
  end if;

  if p_items is not null and jsonb_typeof(p_items) = 'array' then
    for it in select * from jsonb_array_elements(p_items) loop
      iid := nullif(it->>'id','')::bigint;
      if iid is not null then
        update public.contract_items set
          item_type = coalesce(nullif(it->>'item_type',''),'mecra'),
          description = nullif(trim(it->>'description'),''),
          mecra_id = nullif(it->>'mecra_id','')::bigint, unit_id = nullif(it->>'unit_id','')::bigint,
          quantity = coalesce(nullif(it->>'quantity','')::numeric, 1),
          start_date = nullif(it->>'start_date','')::date, end_date = nullif(it->>'end_date','')::date,
          duration_note = nullif(trim(it->>'duration_note'),''),
          unit_price = nullif(it->>'unit_price','')::numeric, line_total = nullif(it->>'line_total','')::numeric,
          note = nullif(trim(it->>'note'),''), sort = coalesce(nullif(it->>'sort','')::int, 0)
        where id = iid and contract_id = cid;
        get diagnostics n = row_count;
        if n = 0 then raise exception 'Kalem bu sözleşmeye ait değil.' using errcode = '42501'; end if;
      else
        insert into public.contract_items (contract_id, item_type, description, mecra_id, unit_id,
          quantity, start_date, end_date, duration_note, unit_price, line_total, note, sort)
        values (cid, coalesce(nullif(it->>'item_type',''),'mecra'), nullif(trim(it->>'description'),''),
          nullif(it->>'mecra_id','')::bigint, nullif(it->>'unit_id','')::bigint,
          coalesce(nullif(it->>'quantity','')::numeric, 1),
          nullif(it->>'start_date','')::date, nullif(it->>'end_date','')::date,
          nullif(trim(it->>'duration_note'),''), nullif(it->>'unit_price','')::numeric,
          nullif(it->>'line_total','')::numeric, nullif(trim(it->>'note'),''),
          coalesce(nullif(it->>'sort','')::int, 0))
        returning id into iid;
      end if;
      keep := keep || iid;
    end loop;
    delete from public.contract_items where contract_id = cid and not (id = any(keep));
  end if;

  if p_doc_ids is not null and array_length(p_doc_ids, 1) > 0 then
    insert into public.document_links (document_id, contract_id)
    select d, cid from unnest(p_doc_ids) d
    on conflict do nothing;
  end if;
  return cid;
end;
$$;
revoke all on function public.contract_save(jsonb, jsonb, bigint[]) from public, anon;
grant execute on function public.contract_save(jsonb, jsonb, bigint[]) to authenticated;

revoke all on function public._trg_contracts_kimlik()     from public, anon, authenticated;
revoke all on function public._trg_contracts_kalem()      from public, anon, authenticated;
revoke all on function public._trg_contract_items_kalem() from public, anon, authenticated;
revoke all on function public._trg_contract_items_koru()  from public, anon, authenticated;
revoke all on function public._trg_contracts_hareket()    from public, anon, authenticated;
