-- =====================================================================
-- Sprint 05 — Baskı / Montaj Operations
-- ---------------------------------------------------------------------
-- Canonical basis:
--   06_DATA_MODEL_AND_MIGRATION_SPEC_v1.0  §13 (work_operations), §16
--   (suppliers), §19 (RLS), §21 (Excel), §22 M5
--   09_V0_SPRINT_PLAN_v1.0                 Sprint 05
--   05_DECISION_LOG_v2.1                   D-216, D-220, D-213
--
-- Operation is a structured CHILD of Work (D-216), not an Entry action
-- and not a separate ERP module. It does NOT require a Booking parent:
-- print-only and install-only Work are both legitimate (01 §12).
--
-- Excel becomes import/export only; the app holds the operational truth
-- (BR-X01/BR-X02).
-- =====================================================================

create table if not exists public.work_operations (
  id                 bigint         generated by default as identity primary key,
  job_id             bigint         not null references public.jobs(id)      on delete cascade,
  operation_type     text           not null,
  status             text           not null default 'planned',
  description        text,
  quantity           numeric(10,2),
  dimensions         text,
  -- Supplier is an Organization relationship role, not a separate master
  -- entity (D-213). Legacy public.suppliers stays untouched for the
  -- existing Tedarikçiler module.
  supplier_org_id    bigint         references public.customers(id) on delete set null,
  unit_id            bigint         references public.units(id)     on delete set null,
  location_text      text,
  planned_date       date,
  completed_at       timestamptz,
  cost               numeric(14,2),
  note               text,
  evidence_urls      jsonb          not null default '[]'::jsonb,
  created_by_team_id bigint         references public.team(id)      on delete set null,
  created_at         timestamptz    not null default now(),
  updated_at         timestamptz
);

comment on table public.work_operations is
  'Baskı / montaj / söküm / field operation rows under a Work (06 s13). Structured child of Work, never a Booking child - a Work may have print-only or install-only operations.';
comment on column public.work_operations.supplier_org_id is
  'Applying/producing Organization (physical customers). Supplier is a relationship role, not a separate institution master (D-213).';
comment on column public.work_operations.evidence_urls is
  'Drive/storage references for proof photos. Files live in Drive; the app keeps the reference (01 §15.4).';

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'work_operations_type_check') then
    alter table public.work_operations add constraint work_operations_type_check
      check (operation_type in ('baski','montaj','sokum','diger'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'work_operations_status_check') then
    alter table public.work_operations add constraint work_operations_status_check
      check (status in ('planned','waiting','in_progress','done','cancelled'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'work_operations_evidence_is_array') then
    alter table public.work_operations add constraint work_operations_evidence_is_array
      check (jsonb_typeof(evidence_urls) = 'array');
  end if;

  if not exists (select 1 from pg_constraint where conname = 'work_operations_quantity_check') then
    alter table public.work_operations add constraint work_operations_quantity_check
      check (quantity is null or quantity >= 0);
  end if;
end
$mig$;

create index if not exists work_operations_job_id_idx       on public.work_operations (job_id);
create index if not exists work_operations_supplier_idx     on public.work_operations (supplier_org_id);
create index if not exists work_operations_unit_idx         on public.work_operations (unit_id);
-- Drives the weekly / monthly / historical period views (07 §13).
create index if not exists work_operations_planned_date_idx on public.work_operations (planned_date);
create index if not exists work_operations_open_idx
  on public.work_operations (planned_date) where status in ('planned','waiting','in_progress');


-- ---------------------------------------------------------------------
-- RLS — internal only (06 §19, Sprint 01 pattern)
-- ---------------------------------------------------------------------
alter table public.work_operations enable row level security;

drop policy if exists work_operations_internal on public.work_operations;
create policy work_operations_internal on public.work_operations
  for all to authenticated
  using (public.is_internal()) with check (public.is_internal());

-- No anon policy: operations are never public.
