-- =====================================================================
-- Product Simplification S8 — Media Operations V2
--
-- Exact, exclusive STATIC placements and concurrent LED campaigns become
-- the operational write model. The monthly `bookings(unit_id, ym)` grid
-- stays as LEGACY evidence and as a month PROJECTION; it is no longer the
-- primary truth that screens write.
--
-- Sellable target (evidence-led, see CURRENT_PRODUCT_DECISIONS_SUPPLEMENT):
--   static exclusive  -> one physical sellable face      = units.id
--   concurrent LED    -> one commercial publication area = alt_mecralar.id
-- `alt_mecralar` already is the stable non-physical level the inventory
-- uses ("M1 Adana LED"), so NO new target table is introduced. Behaviour
-- is STRUCTURAL (`alt_mecralar.occupancy_mode`), never inferred from a name.
-- No fake LED hardware is created: the old single `P3-A` LED row stays only
-- as the anchor of legacy monthly rows and cannot receive a placement.
--
-- Additive only. Legacy columns and rows are kept.
-- =====================================================================

create extension if not exists btree_gist with schema extensions;

-- =====================================================================
-- 1. Structural occupancy behaviour on the sellable-area level
-- =====================================================================
alter table public.alt_mecralar
  add column if not exists occupancy_mode text not null default 'exclusive',
  add column if not exists creative_seconds integer;

alter table public.alt_mecralar drop constraint if exists alt_mecralar_occupancy_mode_check;
alter table public.alt_mecralar add constraint alt_mecralar_occupancy_mode_check
  check (occupancy_mode in ('exclusive','concurrent'));

-- The creative duration is a property of a concurrent publication target,
-- stated once, never re-typed per campaign (PO: 15 s). No frequency, loop
-- share or plays/hour columns: none of them is an established rule.
alter table public.alt_mecralar drop constraint if exists alt_mecralar_creative_seconds_check;
alter table public.alt_mecralar add constraint alt_mecralar_creative_seconds_check
  check (creative_seconds is null
         or (occupancy_mode = 'concurrent' and creative_seconds between 1 and 600));

-- =====================================================================
-- 2. Canonical placement / campaign record
-- =====================================================================
create table if not exists public.media_placements (
  id                   bigint generated by default as identity primary key,
  -- exactly ONE commercial target (explicit FKs, no polymorphic id)
  unit_id              bigint references public.units(id)        on delete restrict,
  alt_mecra_id         bigint references public.alt_mecralar(id) on delete restrict,
  customer_id          bigint not null references public.customers(id) on delete restrict,
  work_id              bigint references public.jobs(id)            on delete set null,
  contract_item_id     bigint references public.contract_items(id)  on delete set null,
  source_quote_id      bigint references public.quotes(id)          on delete set null,
  -- commercial commitment; the temporal state (upcoming/current/ended) is
  -- DERIVED from the dates and is never stored.
  commitment           text not null default 'reserved',
  start_date           date not null,
  end_date             date,                       -- NULL = "Bitiş bilinmiyor"
  note                 text,
  -- provenance only (e.g. historical LED spreadsheet lane "1.ARC"). NOT a
  -- screen id, NOT a slot, NOT used for any validation.
  legacy_lane          text,
  cancelled_at         timestamptz,
  cancelled_by_team_id bigint references public.team(id) on delete set null,
  created_by_team_id   bigint references public.team(id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz,
  constraint media_placements_one_target check (num_nonnulls(unit_id, alt_mecra_id) = 1),
  constraint media_placements_commitment_check
    check (commitment in ('reserved','confirmed','cancelled')),
  constraint media_placements_period_order check (end_date is null or end_date >= start_date),
  constraint media_placements_cancel_meta
    check ((commitment = 'cancelled') = (cancelled_at is not null)),
  constraint media_placements_lane_len check (legacy_lane is null or length(legacy_lane) <= 40),
  -- Static exclusivity is a DATABASE boundary: two blocking placements on
  -- the same face can never overlap, whatever path writes them. Reserved
  -- and confirmed block; cancelled does not. Open end = unbounded range.
  constraint media_placements_no_static_overlap exclude using gist (
    unit_id with =,
    daterange(start_date, end_date, '[]') with &&
  ) where (unit_id is not null and commitment <> 'cancelled')
);

create index if not exists media_placements_unit_idx     on public.media_placements (unit_id)      where unit_id is not null;
create index if not exists media_placements_area_idx     on public.media_placements (alt_mecra_id) where alt_mecra_id is not null;
create index if not exists media_placements_customer_idx on public.media_placements (customer_id);
create index if not exists media_placements_work_idx     on public.media_placements (work_id)      where work_id is not null;
create index if not exists media_placements_dates_idx    on public.media_placements (start_date, end_date);

-- Legacy monthly rows replaced by a canonical placement are kept (history)
-- but stop blocking and stop projecting.
alter table public.bookings
  add column if not exists superseded_by_placement_id bigint
    references public.media_placements(id) on delete set null;
create index if not exists bookings_superseded_idx
  on public.bookings (superseded_by_placement_id) where superseded_by_placement_id is not null;

-- =====================================================================
-- 3. Unified schedule view — the ONE normalized Media query surface
-- =====================================================================
-- Used by Today, Year, Work/Organization context, the notification check,
-- the basic export and (later) Reports V2. security_invoker: RLS of the
-- caller applies, so anon sees nothing.
--
-- precision:
--   exact     real start and end are known
--   open_end  real start known, end explicitly unknown
--   month     only the monthly bucket is trustworthy (legacy) — no day is
--             ever derived from `ym`
-- block_start / block_end: the range a record OCCUPIES for exclusivity.
--   placement -> its own dates (open end = unbounded)
--   legacy    -> its monthly bucket, narrowed to the real period when the
--                real period is known and lies inside that bucket.
create or replace view public.media_schedule
with (security_invoker = true) as
select 'placement'::text                                 as record_kind,
       p.id                                              as placement_id,
       null::bigint                                      as booking_id,
       p.unit_id,
       coalesce(p.alt_mecra_id, u.alt_mecra_id)          as alt_mecra_id,
       coalesce(u.mecra_id, a.mecra_id)                  as mecra_id,
       case when p.alt_mecra_id is not null then 'concurrent' else 'exclusive' end as occupancy_mode,
       p.customer_id, p.work_id, p.contract_item_id, p.source_quote_id,
       p.commitment,
       p.start_date, p.end_date,
       case when p.end_date is null then 'open_end' else 'exact' end as date_precision,
       null::text                                        as ym,
       p.start_date                                      as block_start,
       p.end_date                                        as block_end,
       null::text                                        as period_note,
       p.note, p.legacy_lane,
       p.created_by_team_id, p.created_at, p.updated_at, p.cancelled_at,
       u.name as unit_name, a.name as area_name, m.name as mecra_name,
       c.firma as customer_name, j.title as work_title, a.creative_seconds
  from public.media_placements p
  left join public.units u        on u.id = p.unit_id
  left join public.alt_mecralar a on a.id = coalesce(p.alt_mecra_id, u.alt_mecra_id)
  left join public.mecralar m     on m.id = coalesce(u.mecra_id, a.mecra_id)
  left join public.customers c    on c.id = p.customer_id
  left join public.jobs j         on j.id = p.work_id
union all
select 'legacy', null, b.id,
       b.unit_id, u.alt_mecra_id, u.mecra_id,
       coalesce(a.occupancy_mode, 'exclusive'),
       b.customer_id, b.work_id, null, b.source_quote_id,
       case b.status when 'dolu' then 'confirmed' else 'reserved' end,
       b.period_start, b.period_end,
       case when b.period_start is not null and b.period_end is not null then 'exact'
            when b.period_start is not null then 'open_end'
            else 'month' end,
       b.ym::text,
       case when b.period_start is not null and b.period_end is not null
                 and b.period_start <= k.bitis and b.period_end >= k.bas
            then greatest(b.period_start, k.bas) else k.bas end,
       case when b.period_start is not null and b.period_end is not null
                 and b.period_start <= k.bitis and b.period_end >= k.bas
            then least(b.period_end, k.bitis) else k.bitis end,
       b.period_note, b.note, null,
       null, null, null, null,
       u.name, a.name, m.name, c.firma, j.title, a.creative_seconds
  from public.bookings b
  join public.units u on u.id = b.unit_id
  left join public.alt_mecralar a on a.id = u.alt_mecra_id
  left join public.mecralar m     on m.id = u.mecra_id
  left join public.customers c    on c.id = b.customer_id
  left join public.jobs j         on j.id = b.work_id
  cross join lateral (select to_date(b.ym || '-01', 'YYYY-MM-DD') as bas,
                             (to_date(b.ym || '-01', 'YYYY-MM-DD') + interval '1 month - 1 day')::date as bitis) k
 where b.superseded_by_placement_id is null;

revoke all on public.media_schedule from anon;
grant select on public.media_schedule to authenticated;

-- Conflicts for one static face over [p_start, p_end] (NULL end = open).
-- Returns both canonical placements and still-effective legacy rows.
create or replace function public.media_conflicts(p_unit bigint, p_start date, p_end date,
                                                  p_exclude bigint default null)
returns table (record_kind text, placement_id bigint, booking_id bigint, customer_id bigint,
               block_start date, block_end date, date_precision text, ym text)
language sql stable security invoker
set search_path = public, pg_temp as $$
  select s.record_kind, s.placement_id, s.booking_id, s.customer_id,
         s.block_start, s.block_end, s.date_precision, s.ym
    from public.media_schedule s
   where s.unit_id = p_unit
     and s.occupancy_mode = 'exclusive'
     and s.commitment <> 'cancelled'
     and (p_exclude is null or s.placement_id is distinct from p_exclude)
     and daterange(s.block_start, s.block_end, '[]') && daterange(p_start, p_end, '[]')
   order by s.block_start;
$$;
revoke all on function public.media_conflicts(bigint, date, date, bigint) from public, anon;
grant execute on function public.media_conflicts(bigint, date, date, bigint) to authenticated;

-- Human-readable label of a target, used in movements and conflict lists.
create or replace function public._medya_hedef_adi(p_unit bigint, p_area bigint)
returns text language sql stable security definer
set search_path = public, pg_temp as $$
  select case when p_unit is not null then
           coalesce((select coalesce(a.name, m.name) || ' · ' || u.name
                       from public.units u
                       left join public.alt_mecralar a on a.id = u.alt_mecra_id
                       left join public.mecralar m on m.id = u.mecra_id
                      where u.id = p_unit), '#' || p_unit)
         else coalesce((select a.name from public.alt_mecralar a where a.id = p_area), '#' || p_area)
         end;
$$;
-- Returns only public inventory names; the invoker write paths need it.
revoke all on function public._medya_hedef_adi(bigint, bigint) from public, anon;
grant execute on function public._medya_hedef_adi(bigint, bigint) to authenticated;

create or replace function public._medya_donem(p_start date, p_end date)
returns text language sql immutable as $$
  select to_char(p_start, 'DD.MM.YYYY') || ' – '
         || coalesce(to_char(p_end, 'DD.MM.YYYY'), 'bitiş bilinmiyor');
$$;

-- =====================================================================
-- 4. Integrity trigger (target, Work/Organization, contract item, overlap)
-- =====================================================================
create or replace function public._trg_media_placements_dogrula() returns trigger
language plpgsql security definer
set search_path = public, auth, pg_temp as $$
declare
  v_mode text; v_active boolean; v_unit_area bigint;
  v_orgs int; c record; k record; v_lbl text; v_devral boolean;
begin
  v_devral := coalesce(current_setting('medyapark.eski_devral', true), '') = '1';

  if tg_op = 'INSERT' then
    -- actor comes from the JWT, never from the client payload
    if not public.is_admin() or new.created_by_team_id is null then
      new.created_by_team_id := public.current_team_id();
    end if;
    new.created_at := now();
    new.updated_at := null;
    if new.commitment = 'cancelled' then
      if not public.is_admin() then
        raise exception 'Yeni kayıt iptal durumunda oluşturulamaz.' using errcode = '23514';
      end if;
      new.cancelled_at := coalesce(new.cancelled_at, now());
    else
      new.cancelled_at := null; new.cancelled_by_team_id := null;
    end if;
  else
    if not public.is_admin() and new.created_by_team_id is distinct from old.created_by_team_id then
      raise exception 'Kaydın yazarı değiştirilemez.' using errcode = '42501';
    end if;
    new.created_at := old.created_at;
    if (old.unit_id is null) <> (new.unit_id is null) then
      raise exception 'Hedef türü (statik yüzey / eşzamanlı yayın alanı) değiştirilemez.'
        using errcode = '23514';
    end if;
    if old.commitment = 'cancelled' and new.commitment <> 'cancelled' then
      raise exception 'İptal edilmiş kayıt yeniden etkinleştirilemez; yeni kayıt oluşturun.'
        using errcode = '23514';
    end if;
    if new.commitment = 'cancelled' and old.commitment <> 'cancelled' then
      new.cancelled_at := now(); new.cancelled_by_team_id := public.current_team_id();
    elsif new.commitment = 'cancelled' then
      new.cancelled_at := old.cancelled_at; new.cancelled_by_team_id := old.cancelled_by_team_id;
    end if;
    new.updated_at := now();
  end if;

  -- ---- target ---------------------------------------------------------
  if new.unit_id is not null then
    select coalesce(a.occupancy_mode, 'exclusive'), u.active, u.alt_mecra_id
      into v_mode, v_active, v_unit_area
      from public.units u left join public.alt_mecralar a on a.id = u.alt_mecra_id
     where u.id = new.unit_id;
    if v_mode = 'concurrent' then
      raise exception 'Bu pozisyon eşzamanlı bir yayın alanına ait; kampanya alanın kendisine eklenir.'
        using errcode = '23514';
    end if;
    if not v_active and (tg_op = 'INSERT' or new.unit_id is distinct from old.unit_id) then
      raise exception '%: pozisyon pasif, satışa kapalı.', public._medya_hedef_adi(new.unit_id, null)
        using errcode = '23514';
    end if;
  else
    select occupancy_mode into v_mode from public.alt_mecralar where id = new.alt_mecra_id;
    if v_mode is distinct from 'concurrent' then
      raise exception 'Bu alan eşzamanlı yayın alanı değil; yerleşim tek bir yüzeye yapılır.'
        using errcode = '23514';
    end if;
  end if;

  -- ---- Work <-> Organization: never contradictory ------------------------
  if new.work_id is not null and (tg_op = 'INSERT'
       or new.work_id is distinct from old.work_id or new.customer_id is distinct from old.customer_id) then
    select count(*) into v_orgs from (
      select customer_id from public.jobs where id = new.work_id and customer_id is not null
      union select customer_id from public.work_parties where job_id = new.work_id and customer_id is not null) o;
    if v_orgs > 0 and not exists (
         select 1 from public.jobs where id = new.work_id and customer_id = new.customer_id
         union all
         select 1 from public.work_parties where job_id = new.work_id and customer_id = new.customer_id) then
      raise exception 'Seçilen kurum bu işin taraflarından biri değil.' using errcode = '23514';
    end if;
  end if;

  -- ---- optional contract item: context only, must belong here ----------
  if new.contract_item_id is not null and (tg_op = 'INSERT'
       or new.contract_item_id is distinct from old.contract_item_id
       or new.customer_id is distinct from old.customer_id or new.work_id is distinct from old.work_id) then
    select ct.customer_id, ct.job_id into c
      from public.contract_items ci join public.contracts ct on ct.id = ci.contract_id
     where ci.id = new.contract_item_id;
    if not (c.customer_id = new.customer_id or (new.work_id is not null and c.job_id = new.work_id)) then
      raise exception 'Sözleşme kalemi bu kurum ya da iş ile ilişkili değil.' using errcode = '23514';
    end if;
  end if;

  -- ---- static exclusivity, including still-effective legacy rows --------
  if new.unit_id is not null and new.commitment <> 'cancelled' and (tg_op = 'INSERT'
       or new.unit_id is distinct from old.unit_id or new.start_date is distinct from old.start_date
       or new.end_date is distinct from old.end_date or old.commitment = 'cancelled') then
    select * into k
      from public.media_conflicts(new.unit_id, new.start_date, new.end_date, new.id) x
     where not (v_devral and x.record_kind = 'legacy' and x.customer_id = new.customer_id)
     limit 1;
    if found then
      v_lbl := case when k.record_kind = 'legacy' and k.date_precision = 'month'
                    then 'eski ay kaydı (' || k.ym || ')'
                    else _medya_donem(k.block_start, k.block_end) end;
      raise exception '%: % ile çakışıyor.', public._medya_hedef_adi(new.unit_id, null), v_lbl
        using errcode = '23P01';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_media_placements_dogrula on public.media_placements;
create trigger trg_media_placements_dogrula
  before insert or update on public.media_placements
  for each row execute function public._trg_media_placements_dogrula();

-- Replacing a same-Organization legacy month record is explicit: only when
-- the trusted write path set the flag, and only rows of the SAME customer
-- on the SAME face that the placement covers.
create or replace function public._trg_media_placements_devral() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if coalesce(current_setting('medyapark.eski_devral', true), '') = '1'
     and new.unit_id is not null and new.commitment <> 'cancelled' then
    update public.bookings b set superseded_by_placement_id = new.id
      from public.media_schedule s
     where s.booking_id = b.id and s.record_kind = 'legacy'
       and b.unit_id = new.unit_id and b.customer_id = new.customer_id
       and b.superseded_by_placement_id is null
       and daterange(s.block_start, s.block_end, '[]') && daterange(new.start_date, new.end_date, '[]');
  end if;
  return null;
end;
$$;
drop trigger if exists trg_media_placements_devral on public.media_placements;
create trigger trg_media_placements_devral
  after insert or update on public.media_placements
  for each row execute function public._trg_media_placements_devral();

-- Changing a published area's behaviour under live placements would make
-- existing rows contradictory. Admin-only already (RLS); this guards data.
create or replace function public._trg_alt_mecralar_mod_koru() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if new.occupancy_mode is distinct from old.occupancy_mode then
    if new.occupancy_mode = 'concurrent' and exists (
         select 1 from public.media_placements p join public.units u on u.id = p.unit_id
          where u.alt_mecra_id = new.id and p.commitment <> 'cancelled') then
      raise exception 'Bu alanın yüzeylerinde etkin yerleşim var; yayın davranışı değiştirilemez.'
        using errcode = '23514';
    end if;
    if new.occupancy_mode = 'exclusive' and exists (
         select 1 from public.media_placements p
          where p.alt_mecra_id = new.id and p.commitment <> 'cancelled') then
      raise exception 'Bu alanda etkin kampanya var; yayın davranışı değiştirilemez.'
        using errcode = '23514';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_alt_mecralar_mod_koru on public.alt_mecralar;
create trigger trg_alt_mecralar_mod_koru
  before update of occupancy_mode on public.alt_mecralar
  for each row execute function public._trg_alt_mecralar_mod_koru();

-- History is not silently destroyed by an inventory delete. The FK would
-- refuse anyway; this gives the admin an actionable message instead.
create or replace function public._trg_medya_gecmis_koru() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
begin
  if (tg_table_name = 'units' and exists (select 1 from public.media_placements where unit_id = old.id))
     or (tg_table_name = 'alt_mecralar' and exists (select 1 from public.media_placements where alt_mecra_id = old.id))
     or (tg_table_name = 'customers' and exists (select 1 from public.media_placements where customer_id = old.id)) then
    raise exception 'Bu kaydın mecra yerleşim geçmişi var; silmek yerine pasife alın.'
      using errcode = '23503';
  end if;
  return old;
end;
$$;
drop trigger if exists trg_units_medya_gecmis on public.units;
create trigger trg_units_medya_gecmis before delete on public.units
  for each row execute function public._trg_medya_gecmis_koru();
drop trigger if exists trg_alt_medya_gecmis on public.alt_mecralar;
create trigger trg_alt_medya_gecmis before delete on public.alt_mecralar
  for each row execute function public._trg_medya_gecmis_koru();
drop trigger if exists trg_customers_medya_gecmis on public.customers;
create trigger trg_customers_medya_gecmis before delete on public.customers
  for each row execute function public._trg_medya_gecmis_koru();

-- A legacy monthly write can no longer create a second truth next to an
-- effective placement on the same face (the admin legacy import path).
create or replace function public._trg_bookings_eski_koru() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
declare v_bas date; v_mode text;
begin
  if new.superseded_by_placement_id is not null then return new; end if;
  select coalesce(a.occupancy_mode, 'exclusive') into v_mode
    from public.units u left join public.alt_mecralar a on a.id = u.alt_mecra_id where u.id = new.unit_id;
  if v_mode = 'concurrent' then return new; end if;
  v_bas := to_date(new.ym || '-01', 'YYYY-MM-DD');
  if exists (select 1 from public.media_placements p
              where p.unit_id = new.unit_id and p.commitment <> 'cancelled'
                and daterange(p.start_date, p.end_date, '[]')
                    && daterange(v_bas, (v_bas + interval '1 month - 1 day')::date, '[]')) then
    raise exception '% · %: bu ay için güncel bir yerleşim kaydı var; eski aylık kayıt yazılamaz.',
      public._medya_hedef_adi(new.unit_id, null), new.ym using errcode = '23P01';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_bookings_eski_koru on public.bookings;
create trigger trg_bookings_eski_koru before insert or update of unit_id, ym, status, superseded_by_placement_id
  on public.bookings for each row execute function public._trg_bookings_eski_koru();

revoke all on function public._trg_media_placements_dogrula() from public, anon, authenticated;
revoke all on function public._trg_media_placements_devral()  from public, anon, authenticated;
revoke all on function public._trg_alt_mecralar_mod_koru()    from public, anon, authenticated;
revoke all on function public._trg_medya_gecmis_koru()        from public, anon, authenticated;
revoke all on function public._trg_bookings_eski_koru()       from public, anon, authenticated;

-- =====================================================================
-- 5. RLS — Team operates, Admin owns inventory
-- =====================================================================
alter table public.media_placements enable row level security;
revoke all on public.media_placements from anon;

drop policy if exists s8_media_placements_read   on public.media_placements;
drop policy if exists s8_media_placements_write  on public.media_placements;
drop policy if exists s8_media_placements_modify on public.media_placements;
drop policy if exists s8_media_placements_remove on public.media_placements;
create policy s8_media_placements_read on public.media_placements
  for select to authenticated using (public.is_internal());
create policy s8_media_placements_write on public.media_placements
  for insert to authenticated with check (public.is_internal());
create policy s8_media_placements_modify on public.media_placements
  for update to authenticated using (public.is_internal()) with check (public.is_internal());
-- Established placements are CANCELLED, not deleted. Hard delete stays an
-- admin error-correction tool.
create policy s8_media_placements_remove on public.media_placements
  for delete to authenticated using (public.is_admin());
-- Inventory tables (units / alt_mecralar / mecralar / products) keep their
-- S07 admin-only write policies: occupancy_mode and creative_seconds live
-- on alt_mecralar, so only an admin can change them.

-- =====================================================================
-- 6. Trusted Media activity (Hareketler)
-- =====================================================================
alter table public.entries
  add column if not exists media_placement_id bigint
    references public.media_placements(id) on delete set null;
create index if not exists entries_media_placement_idx
  on public.entries (media_placement_id) where media_placement_id is not null;

alter table public.entries drop constraint if exists entries_target_only_system;
alter table public.entries add constraint entries_target_only_system
  check ((work_operation_id is null and document_id is null and media_placement_id is null)
         or source = 'system');

alter table public.entries drop constraint if exists entries_system_kind_check;
alter table public.entries add constraint entries_system_kind_check check (
  system_kind is null or system_kind in (
    'work_created','work_renamed','work_phase','work_lifecycle','work_contract','work_accounting',
    'operation_created','operation_status',
    'quote_revised','quote_approved',
    'document_added',
    'contract_created','contract_signed','contract_cancelled',
    'media_created','media_changed','media_cancelled'));

-- Internal writer. Work is optional here (a legacy Organization-only
-- placement has none); the Organization is always known.
create or replace function public._medya_hareketi(p_job bigint, p_customer bigint, p_kind text,
                                                  p_body text, p_placement bigint)
returns void language plpgsql security definer
set search_path = public, auth, pg_temp as $$
begin
  if p_body is null then return; end if;
  if coalesce(current_setting('medyapark.medya_sessiz', true), '') = '1' then return; end if;
  insert into public.entries (job_id, customer_id, body, source, system_kind,
                              created_by_team_id, media_placement_id)
  values (p_job, case when p_job is null then p_customer end, p_body, 'system', p_kind,
          public.current_team_id(), p_placement);
end;
$$;
revoke all on function public._medya_hareketi(bigint, bigint, text, text, bigint) from public, anon, authenticated;

-- One movement per logical creation, not per face: a 4-face batch is ONE
-- line ("4 yüzey için ... oluşturuldu"), deep-linked to its first row.
create or replace function public._trg_media_hareket_ekle() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
declare g record; ad text; ne text;
begin
  for g in select work_id, customer_id, commitment, start_date, end_date,
                  (alt_mecra_id is not null) as eszamanli,
                  count(*) as n, min(id) as ilk,
                  array_agg(id order by id) as ids
             from yeni where commitment <> 'cancelled'
            group by 1,2,3,4,5,6 loop
    if g.eszamanli then
      select string_agg(public._medya_hedef_adi(null, p.alt_mecra_id), ', ' order by p.id) into ad
        from yeni p where p.id = any(g.ids);
      ne := ad || ' için yayın eklendi';
    elsif g.n = 1 then
      ne := public._medya_hedef_adi((select unit_id from yeni where id = g.ilk), null)
            || ' için ' || case g.commitment when 'confirmed' then 'kesin kayıt' else 'rezervasyon (opsiyon)' end
            || ' oluşturuldu';
    else
      select string_agg(u.name, ', ' order by u.name) into ad
        from yeni p join public.units u on u.id = p.unit_id where p.id = any(g.ids);
      ne := g.n || ' yüzey için ' || case g.commitment when 'confirmed' then 'kesin kayıt' else 'rezervasyon (opsiyon)' end
            || ' oluşturuldu: ' || ad;
    end if;
    perform public._medya_hareketi(g.work_id, g.customer_id, 'media_created',
      ne || ' · ' || public._medya_donem(g.start_date, g.end_date), g.ilk);
  end loop;
  return null;
end;
$$;
drop trigger if exists trg_media_hareket_ekle on public.media_placements;
create trigger trg_media_hareket_ekle
  after insert on public.media_placements
  referencing new table as yeni
  for each statement execute function public._trg_media_hareket_ekle();

-- Meaningful changes only: period, commitment, face, linked Work,
-- cancellation. Note / contract-item corrections are not movements.
create or replace function public._trg_media_hareket_degis() returns trigger
language plpgsql security definer
set search_path = public, pg_temp as $$
declare hedef text; parca text[] := '{}';
begin
  hedef := public._medya_hedef_adi(new.unit_id, new.alt_mecra_id);
  if new.commitment = 'cancelled' and old.commitment <> 'cancelled' then
    perform public._medya_hareketi(new.work_id, new.customer_id, 'media_cancelled',
      hedef || ' ' || case when new.alt_mecra_id is not null then 'yayını' else 'kaydı' end
      || ' iptal edildi · ' || public._medya_donem(new.start_date, new.end_date), new.id);
    return null;
  end if;
  if new.commitment = 'cancelled' then return null; end if;

  if new.unit_id is distinct from old.unit_id then
    parca := parca || ('yüzey değişti: ' || public._medya_hedef_adi(old.unit_id, null));
  end if;
  if new.start_date = old.start_date and new.end_date is distinct from old.end_date then
    parca := parca || (case
      when new.end_date is null then 'bitiş bilinmiyor olarak işaretlendi'
      when old.end_date is null or new.end_date > old.end_date
        then to_char(new.end_date, 'DD.MM.YYYY') || ' tarihine uzatıldı'
      else to_char(new.end_date, 'DD.MM.YYYY') || ' tarihine kısaltıldı' end);
  elsif new.start_date is distinct from old.start_date or new.end_date is distinct from old.end_date then
    parca := parca || ('dönem değişti: ' || public._medya_donem(old.start_date, old.end_date)
                       || ' → ' || public._medya_donem(new.start_date, new.end_date));
  end if;
  if new.commitment is distinct from old.commitment then
    parca := parca || (case new.commitment when 'confirmed' then 'kesinleşti' else 'opsiyona çevrildi' end);
  end if;
  if new.work_id is distinct from old.work_id then
    parca := parca || ('bağlı iş değişti'::text);
  end if;
  if array_length(parca, 1) is null then return null; end if;
  perform public._medya_hareketi(new.work_id, new.customer_id, 'media_changed',
    hedef || ': ' || array_to_string(parca, '; '), new.id);
  return null;
end;
$$;
drop trigger if exists trg_media_hareket_degis on public.media_placements;
create trigger trg_media_hareket_degis
  after update on public.media_placements
  for each row execute function public._trg_media_hareket_degis();

revoke all on function public._trg_media_hareket_ekle()  from public, anon, authenticated;
revoke all on function public._trg_media_hareket_degis() from public, anon, authenticated;

-- =====================================================================
-- 7. Trusted write paths (SECURITY INVOKER: RLS + every trigger apply)
-- =====================================================================
-- All-or-nothing batch. Every target is pre-checked; if ANY target has a
-- problem, nothing is written and each problem is reported per target.
-- Otherwise ONE insert statement writes one row per target.
create or replace function public.media_placements_create(p_common jsonb, p_targets jsonb)
returns jsonb language plpgsql security invoker
set search_path = public, pg_temp as $$
declare
  t jsonb; n int := 0; v_customer bigint; v_work bigint; v_start date; v_end date;
  v_commit text; v_devral boolean; sorun jsonb := '[]'::jsonb; cak jsonb;
  v_unit bigint; v_area bigint; v_mode text; v_active boolean; ids bigint[];
  v_seen text[] := '{}';
begin
  if not public.is_internal() then
    raise exception 'Bu işlem için ekip üyesi olmalısınız.' using errcode = '42501';
  end if;
  v_work     := nullif(p_common->>'work_id', '')::bigint;
  v_customer := nullif(p_common->>'customer_id', '')::bigint;
  v_start    := nullif(p_common->>'start_date', '')::date;
  v_end      := nullif(p_common->>'end_date', '')::date;
  v_commit   := coalesce(nullif(p_common->>'commitment', ''), 'reserved');
  v_devral   := coalesce((p_common->>'eski_devral')::boolean, false);

  if v_customer is null and v_work is not null then
    select customer_id into v_customer from public.jobs where id = v_work;
  end if;
  if v_customer is null then
    raise exception 'Kurum seçilmeli.' using errcode = '22023';
  end if;
  if v_start is null then
    raise exception 'Başlangıç tarihi zorunlu.' using errcode = '22023';
  end if;
  if v_end is not null and v_end < v_start then
    raise exception 'Bitiş tarihi başlangıçtan önce olamaz.' using errcode = '22023';
  end if;
  if v_commit not in ('reserved','confirmed') then
    raise exception 'Geçersiz durum.' using errcode = '22023';
  end if;
  if jsonb_typeof(p_targets) <> 'array' or jsonb_array_length(p_targets) = 0 then
    raise exception 'En az bir yüzey ya da yayın alanı seçilmeli.' using errcode = '22023';
  end if;
  if jsonb_array_length(p_targets) > 120 then
    raise exception 'Tek seferde en fazla 120 hedef kaydedilebilir.' using errcode = '22023';
  end if;

  for t in select * from jsonb_array_elements(p_targets) loop
    n := n + 1;
    v_unit := nullif(t->>'unit_id', '')::bigint;
    v_area := nullif(t->>'alt_mecra_id', '')::bigint;
    if num_nonnulls(v_unit, v_area) <> 1 then
      raise exception 'Hedef %: tek bir yüzey ya da yayın alanı olmalı.', n using errcode = '22023';
    end if;
    if (coalesce(v_unit::text, 'a' || v_area)) = any(v_seen) then
      raise exception 'Aynı hedef iki kez seçildi.' using errcode = '22023';
    end if;
    v_seen := v_seen || coalesce(v_unit::text, 'a' || v_area);

    if v_unit is not null then
      select coalesce(a.occupancy_mode, 'exclusive'), u.active into v_mode, v_active
        from public.units u left join public.alt_mecralar a on a.id = u.alt_mecra_id where u.id = v_unit;
      if v_mode is null then
        sorun := sorun || jsonb_build_object('unit_id', v_unit, 'hedef', '#' || v_unit, 'neden', 'Yüzey bulunamadı.');
        continue;
      end if;
      if v_mode = 'concurrent' then
        sorun := sorun || jsonb_build_object('unit_id', v_unit, 'hedef', public._medya_hedef_adi(v_unit, null),
                                             'neden', 'Eşzamanlı yayın alanına ait; kampanya alana eklenir.');
        continue;
      end if;
      if not v_active then
        sorun := sorun || jsonb_build_object('unit_id', v_unit, 'hedef', public._medya_hedef_adi(v_unit, null),
                                             'neden', 'Pozisyon pasif, satışa kapalı.');
        continue;
      end if;
      select jsonb_agg(jsonb_build_object(
               'tur', x.record_kind, 'placement_id', x.placement_id, 'booking_id', x.booking_id,
               'customer_id', x.customer_id, 'firma', c.firma,
               'bas', x.block_start, 'bit', x.block_end, 'precision', x.date_precision, 'ym', x.ym,
               'devralinabilir', (x.record_kind = 'legacy' and x.customer_id = v_customer)))
        into cak
        from public.media_conflicts(v_unit, v_start, v_end) x
        left join public.customers c on c.id = x.customer_id
       where not (v_devral and x.record_kind = 'legacy' and x.customer_id = v_customer);
      if cak is not null then
        sorun := sorun || jsonb_build_object('unit_id', v_unit, 'hedef', public._medya_hedef_adi(v_unit, null),
                                             'neden', 'Çakışma', 'cakismalar', cak);
      end if;
    else
      select occupancy_mode into v_mode from public.alt_mecralar where id = v_area;
      if v_mode is distinct from 'concurrent' then
        sorun := sorun || jsonb_build_object('alt_mecra_id', v_area, 'hedef', public._medya_hedef_adi(null, v_area),
                                             'neden', 'Eşzamanlı yayın alanı değil.');
      end if;
    end if;
  end loop;

  if jsonb_array_length(sorun) > 0 then
    return jsonb_build_object('ok', false, 'sorunlar', sorun);
  end if;

  if v_devral then perform set_config('medyapark.eski_devral', '1', true); end if;
  with ins as (
    insert into public.media_placements (unit_id, alt_mecra_id, customer_id, work_id, contract_item_id,
                                         commitment, start_date, end_date, note)
    select nullif(x->>'unit_id', '')::bigint, nullif(x->>'alt_mecra_id', '')::bigint,
           v_customer, v_work, nullif(p_common->>'contract_item_id', '')::bigint,
           v_commit, v_start, v_end, nullif(trim(p_common->>'note'), '')
      from jsonb_array_elements(p_targets) with ordinality e(x, i)
     order by i
    returning id)
  select array_agg(id order by id) into ids from ins;
  perform set_config('medyapark.eski_devral', '', true);

  return jsonb_build_object('ok', true, 'ids', to_jsonb(ids));
end;
$$;
revoke all on function public.media_placements_create(jsonb, jsonb) from public, anon;
grant execute on function public.media_placements_create(jsonb, jsonb) to authenticated;

-- Single-row edit / cancel with the same structured conflict answer.
create or replace function public.media_placement_update(p_id bigint, p_patch jsonb)
returns jsonb language plpgsql security invoker
set search_path = public, pg_temp as $$
declare p record; v_start date; v_end date; v_unit bigint; v_devral boolean; cak jsonb; n int;
begin
  if not public.is_internal() then
    raise exception 'Bu işlem için ekip üyesi olmalısınız.' using errcode = '42501';
  end if;
  select * into p from public.media_placements where id = p_id;
  if not found then raise exception 'Kayıt bulunamadı.' using errcode = 'P0002'; end if;

  v_start  := coalesce(nullif(p_patch->>'start_date', '')::date, p.start_date);
  v_end    := case when p_patch ? 'end_date' then nullif(p_patch->>'end_date', '')::date else p.end_date end;
  v_unit   := coalesce(nullif(p_patch->>'unit_id', '')::bigint, p.unit_id);
  v_devral := coalesce((p_patch->>'eski_devral')::boolean, false);

  if v_unit is not null and coalesce(p_patch->>'commitment', p.commitment) <> 'cancelled' then
    select jsonb_agg(jsonb_build_object(
             'tur', x.record_kind, 'placement_id', x.placement_id, 'booking_id', x.booking_id,
             'customer_id', x.customer_id, 'firma', c.firma,
             'bas', x.block_start, 'bit', x.block_end, 'precision', x.date_precision, 'ym', x.ym,
             'devralinabilir', (x.record_kind = 'legacy' and x.customer_id = p.customer_id)))
      into cak
      from public.media_conflicts(v_unit, v_start, v_end, p_id) x
      left join public.customers c on c.id = x.customer_id
     where not (v_devral and x.record_kind = 'legacy' and x.customer_id = p.customer_id);
    if cak is not null then
      return jsonb_build_object('ok', false, 'sorunlar', jsonb_build_array(jsonb_build_object(
        'unit_id', v_unit, 'hedef', public._medya_hedef_adi(v_unit, null), 'neden', 'Çakışma',
        'cakismalar', cak)));
    end if;
  end if;

  if v_devral then perform set_config('medyapark.eski_devral', '1', true); end if;
  update public.media_placements set
    unit_id          = v_unit,
    start_date       = v_start,
    end_date         = v_end,
    commitment       = coalesce(nullif(p_patch->>'commitment', ''), commitment),
    work_id          = case when p_patch ? 'work_id' then nullif(p_patch->>'work_id', '')::bigint else work_id end,
    customer_id      = coalesce(nullif(p_patch->>'customer_id', '')::bigint, customer_id),
    contract_item_id = case when p_patch ? 'contract_item_id'
                            then nullif(p_patch->>'contract_item_id', '')::bigint else contract_item_id end,
    note             = case when p_patch ? 'note' then nullif(trim(p_patch->>'note'), '') else note end
   where id = p_id;
  get diagnostics n = row_count;
  perform set_config('medyapark.eski_devral', '', true);
  if n = 0 then raise exception 'Bu kaydı değiştirme yetkiniz yok.' using errcode = '42501'; end if;
  return jsonb_build_object('ok', true, 'id', p_id);
end;
$$;
revoke all on function public.media_placement_update(bigint, jsonb) from public, anon;
grant execute on function public.media_placement_update(bigint, jsonb) to authenticated;

-- =====================================================================
-- 8. Public availability — privacy-safe monthly projection
-- =====================================================================
-- Same three columns as before (unit_id, ym, status) so the public site is
-- untouched. Owner-rights view (as before): anon never reads the base
-- tables, only this projection — no Organization, Work, contract, note or
-- exact period.
--   static placement -> every month it touches (a partial month counts as
--                       unavailable: conservative). Open end -> projected
--                       24 months past the current month.
--   legacy month row -> still counts, unless superseded.
--   concurrent LED   -> EXCLUDED. Campaign presence is not "full" and no
--                       capacity rule exists, so the public cart treats the
--                       LED area as requestable; sale is confirmed manually.
create or replace view public.booking_availability_public as
with eski as (
  select b.unit_id, b.ym::text as ym, b.status
    from public.bookings b
    join public.units u on u.id = b.unit_id
    left join public.alt_mecralar a on a.id = u.alt_mecra_id
   where u.active and b.superseded_by_placement_id is null
     and coalesce(a.occupancy_mode, 'exclusive') = 'exclusive'
), yeni as (
  select p.unit_id, to_char(m, 'YYYY-MM') as ym,
         case p.commitment when 'confirmed' then 'dolu' else 'rezerve' end as status
    from public.media_placements p
    join public.units u on u.id = p.unit_id
    cross join lateral generate_series(
      date_trunc('month', p.start_date::timestamp),
      date_trunc('month', coalesce(p.end_date::timestamp,
                                   date_trunc('month', localtimestamp) + interval '24 months')),
      interval '1 month') m
   where p.unit_id is not null and p.commitment <> 'cancelled' and u.active
), tum as (select * from eski union all select * from yeni)
select unit_id, ym::character(7) as ym,
       case when bool_or(status = 'dolu') then 'dolu' else 'rezerve' end as status
  from tum
 group by unit_id, ym;

-- =====================================================================
-- 9. approve_quote(): writes canonical placements, not monthly bookings
-- =====================================================================
-- A public quote item sells ONE calendar month (`ym`), so the commercial
-- unit itself is the month: the placement is that month's first..last day.
-- Consecutive months of the same face in the same Offer become ONE
-- placement. A face in a concurrent area becomes ONE campaign on the area.
-- Conflicts are reported and skipped exactly as before; a same-customer
-- legacy month row is replaced (superseded), not duplicated.
create or replace function public.approve_quote(p_quote_id bigint)
returns jsonb language plpgsql
set search_path = public, pg_temp as $$
declare
  q            record;
  r            record;
  cust_id      bigint;
  v_work_id    bigint;
  m_id         bigint;
  reserved     int     := 0;
  skipped      int     := 0;
  conflicts    text[]  := '{}';
  created_work boolean := false;
  job_title    text;
  cur_phase    text;
  phase_rank   jsonb   := '{"temas_takip":0,"teklif":1,"baski":2,"montaj":3,"yayinda_aktif":4}';
begin
  select * into q from quotes where id = p_quote_id;
  if not found then
    return jsonb_build_object('done', false, 'error', 'quote_not_found');
  end if;

  if q.status = 'onaylandi' then
    return jsonb_build_object(
      'done', true, 'already_approved', true,
      'reserved', 0, 'skipped', 0, 'conflicts', '[]'::jsonb,
      'customer_id', q.customer_id, 'work_id', q.work_id);
  end if;

  cust_id := q.customer_id;
  if cust_id is null and coalesce(q.eposta,'') <> '' then
    select id into cust_id from customers where eposta = q.eposta limit 1;
  end if;
  if cust_id is null and coalesce(q.firma,'') <> '' then
    select id into cust_id from customers where firma = q.firma limit 1;
  end if;
  if cust_id is null then
    insert into customers (firma, telefon, eposta, source_type, source_ref)
    values (coalesce(nullif(q.firma,''), nullif(q.customer_name,''), 'Müşteri'),
            q.telefon, q.eposta, 'quote', 'quotes#' || p_quote_id)
    returning id into cust_id;
    if coalesce(nullif(trim(q.customer_name),''),'') <> '' then
      insert into contacts (customer_id, name, phone, email, is_primary, source_type, source_ref)
      values (cust_id, trim(q.customer_name), q.telefon, q.eposta, true,
              'quote', 'quotes#' || p_quote_id);
    end if;
  end if;
  if q.customer_id is null then
    update quotes set customer_id = cust_id where id = p_quote_id;
  end if;

  v_work_id := q.work_id;
  select mecra_id into m_id
    from units
   where id = (select unit_id from quote_items
                where quote_id = p_quote_id and unit_id is not null limit 1);
  if v_work_id is null then
    job_title := coalesce(nullif(q.firma,''), nullif(q.customer_name,''), 'Müşteri')
                 || ' — Teklif #' || p_quote_id;
    insert into jobs (title, customer_id, mecra_id, status, lifecycle_status, note)
    values (job_title, cust_id, m_id, 'teklif', 'acik',
            'Onaylanan tekliften otomatik oluşturuldu.')
    returning id into v_work_id;
    created_work := true;
    update quotes set work_id = v_work_id where id = p_quote_id;
    insert into work_parties (job_id, customer_id, role)
    values (v_work_id, cust_id, 'account')
    on conflict do nothing;
  end if;

  -- Consecutive-month runs per target (gaps-and-islands on month index).
  perform set_config('medyapark.eski_devral', '1', true);
  for r in
    with it as (
      select distinct qi.unit_id, qi.ym,
             case when coalesce(a.occupancy_mode,'exclusive') = 'concurrent' then u.alt_mecra_id end as area_id,
             public._medya_hedef_adi(qi.unit_id, null) as unit_name,
             to_date(qi.ym || '-01', 'YYYY-MM-DD') as ay
        from quote_items qi
        join units u on u.id = qi.unit_id
        left join alt_mecralar a on a.id = u.alt_mecra_id
       where qi.quote_id = p_quote_id and qi.unit_id is not null and qi.ym is not null
    ), hedef as (
      select distinct case when area_id is null then unit_id end as unit_id, area_id,
             case when area_id is null then unit_name
                  else (select name from alt_mecralar where id = area_id) end as ad, ay
        from it
    ), ada as (
      select *, (extract(year from ay) * 12 + extract(month from ay))::int
                - row_number() over (partition by unit_id, area_id order by ay)::int as grp
        from hedef
    )
    select unit_id, area_id, min(ad) as ad, min(ay) as bas,
           (max(ay) + interval '1 month - 1 day')::date as bit
      from ada group by unit_id, area_id, grp
      order by 1, 2, 4
  loop
    begin
      if r.unit_id is not null and exists (
           select 1 from media_conflicts(r.unit_id, r.bas, r.bit) x
            where not (x.record_kind = 'legacy' and x.customer_id = cust_id)) then
        conflicts := array_append(conflicts, r.ad || ' · ' || to_char(r.bas, 'MM.YYYY')
                     || case when r.bit > (r.bas + interval '1 month')::date
                             then '–' || to_char(r.bit, 'MM.YYYY') else '' end);
        skipped := skipped + 1;
        continue;
      end if;
      insert into media_placements (unit_id, alt_mecra_id, customer_id, work_id, commitment,
                                    start_date, end_date, source_quote_id)
      values (r.unit_id, r.area_id, cust_id, v_work_id, 'confirmed', r.bas, r.bit, p_quote_id);
      reserved := reserved + 1;
    exception when exclusion_violation or check_violation then
      conflicts := array_append(conflicts, r.ad || ' · ' || to_char(r.bas, 'MM.YYYY'));
      skipped := skipped + 1;
    end;
  end loop;
  perform set_config('medyapark.eski_devral', '', true);

  select status into cur_phase from jobs where id = v_work_id;
  if coalesce((phase_rank ->> cur_phase)::int, 0) < 1 then
    update jobs set status = 'teklif' where id = v_work_id;
  end if;

  update quotes set status = 'onaylandi' where id = p_quote_id;

  insert into entries (job_id, customer_id, body, source, source_ref)
  values (v_work_id, cust_id,
          'Teklif #' || p_quote_id || ' onaylandı'
          || case when reserved > 0 then ' · ' || reserved || ' mecra kaydı oluşturuldu' else '' end
          || case when skipped  > 0 then ' · ' || skipped  || ' kayıt çakışma nedeniyle atlandı' else '' end,
          'system', 'quotes#' || p_quote_id);

  return jsonb_build_object(
    'done',         true,
    'reserved',     reserved,
    'skipped',      skipped,
    'conflicts',    to_jsonb(conflicts),
    'customer_id',  cust_id,
    'work_id',      v_work_id,
    'created_work', created_work);
end
$$;

-- =====================================================================
-- 10. Data: M1 LED is a concurrent publication area; deterministic legacy
--     exact-period consolidation. Replayed after the company-data seed by
--     supabase/seeds/98_ps8_media_backfill.sql (db reset runs migrations
--     against an EMPTY database, so here these are no-ops locally).
-- =====================================================================
update public.alt_mecralar
   set occupancy_mode = 'concurrent', creative_seconds = 15
 where id = 4 and name = 'M1 Adana LED' and occupancy_mode = 'exclusive'
   and not exists (select 1 from public.media_placements p join public.units u on u.id = p.unit_id
                    where u.alt_mecra_id = 4);

create or replace function public._ps8_eski_kesin_birlestir()
returns int language plpgsql security definer
set search_path = public, pg_temp as $$
declare g record; v_id bigint; n int := 0;
begin
  perform set_config('medyapark.eski_devral', '1', true);
  perform set_config('medyapark.medya_sessiz', '1', true);   -- a migration is not a business event
  for g in
    select b.unit_id, b.customer_id, b.period_start as ps, b.period_end as pe, b.status,
           array_agg(b.id order by b.ym) as ids, array_agg(b.ym::text order by b.ym) as yms,
           count(distinct b.work_id) as is_say, max(b.work_id) as work_id,
           max(b.source_quote_id) as quote_id
      from public.bookings b
      join public.units u on u.id = b.unit_id
      left join public.alt_mecralar a on a.id = u.alt_mecra_id
     where b.period_start is not null and b.period_end is not null
       and b.customer_id is not null and b.superseded_by_placement_id is null
       and u.active and coalesce(a.occupancy_mode, 'exclusive') = 'exclusive'
     group by b.unit_id, b.customer_id, b.period_start, b.period_end, b.status
  loop
    -- deterministic only: the rows cover EXACTLY the months the one real
    -- period spans, and at most one Work is involved.
    if g.yms is distinct from (select array_agg(to_char(m, 'YYYY-MM') order by m)
                                 from generate_series(date_trunc('month', g.ps::timestamp),
                                                      date_trunc('month', g.pe::timestamp),
                                                      interval '1 month') m)
       or g.is_say > 1 then
      continue;
    end if;
    begin
      insert into public.media_placements (unit_id, customer_id, work_id, commitment,
                                           start_date, end_date, source_quote_id, note)
      values (g.unit_id, g.customer_id, g.work_id,
              case g.status when 'dolu' then 'confirmed' else 'reserved' end,
              g.ps, g.pe, g.quote_id, 'Eski aylık kayıtlardan birleştirildi')
      returning id into v_id;
      update public.bookings set superseded_by_placement_id = v_id where id = any(g.ids);
      n := n + 1;
    exception when others then
      raise notice 'PS8: eski kayıt birleştirilemedi (unit %, %): %', g.unit_id, g.ps, sqlerrm;
    end;
  end loop;
  perform set_config('medyapark.eski_devral', '', true);
  perform set_config('medyapark.medya_sessiz', '', true);
  return n;
end;
$$;
revoke all on function public._ps8_eski_kesin_birlestir() from public, anon, authenticated;
select public._ps8_eski_kesin_birlestir();
